# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumeroffset',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
