# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AgentMessage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import PostgresType_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='AgentMessage.proto',
  package='',
  serialized_pb='\n\x12\x41gentMessage.proto\x1a\x12PostgresType.proto\"\xae\x05\n\x0c\x41gentMessage\x12 \n\ttimeStamp\x18\x01 \x02(\x03\x42\r\x82\xb5\x18\ttimestamp\x12\x1b\n\tagentGUID\x18\x02 \x02(\tB\x08\x82\xb5\x18\x04uuid\x12\x33\n\nidentifier\x18\x03 \x02(\x0e\x32\x1f.AgentMessage.MessageIdentifier\x12\'\n\x04type\x18\x04 \x02(\x0e\x32\x19.AgentMessage.MessageType\x12\x0e\n\x06source\x18\x05 \x02(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x02(\t\x12\x0e\n\x06siteId\x18\x07 \x01(\t\x12\x16\n\x04uuid\x18\x08 \x01(\tB\x08\x82\xb5\x18\x04uuid\x12\x15\n\nerrorValue\x18\t \x01(\x03:\x01\x30\"\xd3\x02\n\x11MessageIdentifier\x12\x13\n\x0fMESSAGE_SUCCESS\x10\x00\x12\x1a\n\x16MESSAGE_FILE_NOT_FOUND\x10\x01\x12 \n\x1cMESSAGE_WMI_SERVICE_DISABLED\x10\x02\x12\x15\n\x11MESSAGE_WMI_ERROR\x10\x03\x12!\n\x1dMESSAGE_CLIENTTIMECLOCKCHANGE\x10\x04\x12\x1a\n\x16MESSAGE_BROKERDATALOSS\x10\x05\x12\x1b\n\x17MESSAGE_EVENTLOGDAMAGED\x10\x06\x12*\n&MESSAGE_AGENTSTATUS_TIMER_DID_NOT_FIRE\x10\x07\x12*\n&MESSAGE_FILECONTENTS_TRANSMISSION_LOSS\x10\x08\x12 \n\x1cMESSAGE_MD5_GENERATION_ERROR\x10\t\"G\n\x0bMessageType\x12\x0e\n\nTYPE_ERROR\x10\x01\x12\x10\n\x0cTYPE_WARNING\x10\x02\x12\x16\n\x12TYPE_INFORMATIONAL\x10\x03\x42\x39\n\"com.ziften.server.protocol.messageB\x13\x41gentMessageMessage')



_AGENTMESSAGE_MESSAGEIDENTIFIER = _descriptor.EnumDescriptor(
  name='MessageIdentifier',
  full_name='AgentMessage.MessageIdentifier',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MESSAGE_SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MESSAGE_FILE_NOT_FOUND', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MESSAGE_WMI_SERVICE_DISABLED', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MESSAGE_WMI_ERROR', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MESSAGE_CLIENTTIMECLOCKCHANGE', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MESSAGE_BROKERDATALOSS', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MESSAGE_EVENTLOGDAMAGED', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MESSAGE_AGENTSTATUS_TIMER_DID_NOT_FIRE', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MESSAGE_FILECONTENTS_TRANSMISSION_LOSS', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MESSAGE_MD5_GENERATION_ERROR', index=9, number=9,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=317,
  serialized_end=656,
)

_AGENTMESSAGE_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='AgentMessage.MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TYPE_ERROR', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TYPE_WARNING', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TYPE_INFORMATIONAL', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=658,
  serialized_end=729,
)


_AGENTMESSAGE = _descriptor.Descriptor(
  name='AgentMessage',
  full_name='AgentMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='AgentMessage.timeStamp', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')),
    _descriptor.FieldDescriptor(
      name='agentGUID', full_name='AgentMessage.agentGUID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='identifier', full_name='AgentMessage.identifier', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='AgentMessage.type', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source', full_name='AgentMessage.source', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='AgentMessage.description', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='siteId', full_name='AgentMessage.siteId', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='AgentMessage.uuid', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='errorValue', full_name='AgentMessage.errorValue', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _AGENTMESSAGE_MESSAGEIDENTIFIER,
    _AGENTMESSAGE_MESSAGETYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=43,
  serialized_end=729,
)

_AGENTMESSAGE.fields_by_name['identifier'].enum_type = _AGENTMESSAGE_MESSAGEIDENTIFIER
_AGENTMESSAGE.fields_by_name['type'].enum_type = _AGENTMESSAGE_MESSAGETYPE
_AGENTMESSAGE_MESSAGEIDENTIFIER.containing_type = _AGENTMESSAGE;
_AGENTMESSAGE_MESSAGETYPE.containing_type = _AGENTMESSAGE;
DESCRIPTOR.message_types_by_name['AgentMessage'] = _AGENTMESSAGE

class AgentMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AGENTMESSAGE

  # @@protoc_insertion_point(class_scope:AgentMessage)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\"com.ziften.server.protocol.messageB\023AgentMessageMessage')
_AGENTMESSAGE.fields_by_name['timeStamp'].has_options = True
_AGENTMESSAGE.fields_by_name['timeStamp']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')
_AGENTMESSAGE.fields_by_name['agentGUID'].has_options = True
_AGENTMESSAGE.fields_by_name['agentGUID']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
_AGENTMESSAGE.fields_by_name['uuid'].has_options = True
_AGENTMESSAGE.fields_by_name['uuid']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
# @@protoc_insertion_point(module_scope)
