# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AgentStatus.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import PostgresType_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='AgentStatus.proto',
  package='',
  serialized_pb='\n\x11\x41gentStatus.proto\x1a\x12PostgresType.proto\"\xc1\x02\n\x0b\x41gentStatus\x12 \n\ttimeStamp\x18\x01 \x02(\x03\x42\r\x82\xb5\x18\ttimestamp\x12\x1b\n\tagentGUID\x18\x02 \x02(\tB\x08\x82\xb5\x18\x04uuid\x12\x38\n\x0b\x61gentStatus\x18\x03 \x02(\x0e\x32#.AgentStatus.AgentStatusMessageType\x12\x14\n\x0coldAgentGUID\x18\x08 \x01(\t\x12\x0e\n\x06siteId\x18\t \x01(\t\x12\x14\n\x0c\x63omputerName\x18\n \x01(\t\x12\x16\n\x04uuid\x18\x0b \x01(\tB\x08\x82\xb5\x18\x04uuid\"e\n\x16\x41gentStatusMessageType\x12\x10\n\x0c\x41GENTSTARTED\x10\x00\x12\x10\n\x0c\x41GENTSTOPPED\x10\x01\x12\x13\n\x0f\x41GENTGUIDCHANGE\x10\x05\x12\x12\n\x0e\x41GENTHEARTBEAT\x10\x06\x42\x38\n\"com.ziften.server.protocol.messageB\x12\x41gentStatusMessage')



_AGENTSTATUS_AGENTSTATUSMESSAGETYPE = _descriptor.EnumDescriptor(
  name='AgentStatusMessageType',
  full_name='AgentStatus.AgentStatusMessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AGENTSTARTED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AGENTSTOPPED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AGENTGUIDCHANGE', index=2, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AGENTHEARTBEAT', index=3, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=262,
  serialized_end=363,
)


_AGENTSTATUS = _descriptor.Descriptor(
  name='AgentStatus',
  full_name='AgentStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='AgentStatus.timeStamp', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')),
    _descriptor.FieldDescriptor(
      name='agentGUID', full_name='AgentStatus.agentGUID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='agentStatus', full_name='AgentStatus.agentStatus', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='oldAgentGUID', full_name='AgentStatus.oldAgentGUID', index=3,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='siteId', full_name='AgentStatus.siteId', index=4,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='computerName', full_name='AgentStatus.computerName', index=5,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='AgentStatus.uuid', index=6,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _AGENTSTATUS_AGENTSTATUSMESSAGETYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=42,
  serialized_end=363,
)

_AGENTSTATUS.fields_by_name['agentStatus'].enum_type = _AGENTSTATUS_AGENTSTATUSMESSAGETYPE
_AGENTSTATUS_AGENTSTATUSMESSAGETYPE.containing_type = _AGENTSTATUS;
DESCRIPTOR.message_types_by_name['AgentStatus'] = _AGENTSTATUS

class AgentStatus(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AGENTSTATUS

  # @@protoc_insertion_point(class_scope:AgentStatus)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\"com.ziften.server.protocol.messageB\022AgentStatusMessage')
_AGENTSTATUS.fields_by_name['timeStamp'].has_options = True
_AGENTSTATUS.fields_by_name['timeStamp']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')
_AGENTSTATUS.fields_by_name['agentGUID'].has_options = True
_AGENTSTATUS.fields_by_name['agentGUID']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
_AGENTSTATUS.fields_by_name['uuid'].has_options = True
_AGENTSTATUS.fields_by_name['uuid']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
# @@protoc_insertion_point(module_scope)
