# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AgentSettingsResponse.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = _descriptor.FileDescriptor(
  name='AgentSettingsResponse.proto',
  package='',
  serialized_pb='\n\x1b\x41gentSettingsResponse.proto\x1a\x12PostgresType.proto\"\xa4\x02\n\x15\x41gentSettingsResponse\x12 \n\ttimeStamp\x18\x01 \x02(\x03\x42\r\x82\xb5\x18\ttimestamp\x12\x1b\n\tagentGUID\x18\x02 \x02(\tB\x08\x82\xb5\x18\x04uuid\x12\x13\n\x0bserverJobID\x18\x03 \x01(\x03\x12\x42\n\x0esettingsResult\x18\x04 \x02(\x0e\x32*.AgentSettingsResponse.AgentSettingsResult\x12\x0e\n\x06siteId\x18\x05 \x01(\t\x12\x16\n\x04uuid\x18\x06 \x01(\tB\x08\x82\xb5\x18\x04uuid\"K\n\x13\x41gentSettingsResult\x12\x19\n\x15\x41GENTSETTINGS_SUCCESS\x10\x00\x12\x19\n\x15\x41GENTSETTINGS_FAILURE\x10\x01\x42\x42\n\"com.ziften.server.protocol.messageB\x1c\x41gentSettingsResponseMessage')



_AGENTSETTINGSRESPONSE_AGENTSETTINGSRESULT = _descriptor.EnumDescriptor(
  name='AgentSettingsResult',
  full_name='AgentSettingsResponse.AgentSettingsResult',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AGENTSETTINGS_SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AGENTSETTINGS_FAILURE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=269,
  serialized_end=344,
)


_AGENTSETTINGSRESPONSE = _descriptor.Descriptor(
  name='AgentSettingsResponse',
  full_name='AgentSettingsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='AgentSettingsResponse.timeStamp', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')),
    _descriptor.FieldDescriptor(
      name='agentGUID', full_name='AgentSettingsResponse.agentGUID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='serverJobID', full_name='AgentSettingsResponse.serverJobID', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='settingsResult', full_name='AgentSettingsResponse.settingsResult', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='siteId', full_name='AgentSettingsResponse.siteId', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='AgentSettingsResponse.uuid', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _AGENTSETTINGSRESPONSE_AGENTSETTINGSRESULT,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=52,
  serialized_end=344,
)

_AGENTSETTINGSRESPONSE.fields_by_name['settingsResult'].enum_type = _AGENTSETTINGSRESPONSE_AGENTSETTINGSRESULT
_AGENTSETTINGSRESPONSE_AGENTSETTINGSRESULT.containing_type = _AGENTSETTINGSRESPONSE;
DESCRIPTOR.message_types_by_name['AgentSettingsResponse'] = _AGENTSETTINGSRESPONSE

class AgentSettingsResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AGENTSETTINGSRESPONSE

  # @@protoc_insertion_point(class_scope:AgentSettingsResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\"com.ziften.server.protocol.messageB\034AgentSettingsResponseMessage')
_AGENTSETTINGSRESPONSE.fields_by_name['timeStamp'].has_options = True
_AGENTSETTINGSRESPONSE.fields_by_name['timeStamp']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')
_AGENTSETTINGSRESPONSE.fields_by_name['agentGUID'].has_options = True
_AGENTSETTINGSRESPONSE.fields_by_name['agentGUID']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
_AGENTSETTINGSRESPONSE.fields_by_name['uuid'].has_options = True
_AGENTSETTINGSRESPONSE.fields_by_name['uuid']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
# @@protoc_insertion_point(module_scope)
