# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExtensionCatalogRequest.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import PostgresType_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ExtensionCatalogRequest.proto',
  package='',
  serialized_pb='\n\x1d\x45xtensionCatalogRequest.proto\x1a\x12PostgresType.proto\"\xd4\x01\n\x17\x45xtensionCatalogRequest\x12 \n\ttimeStamp\x18\x01 \x01(\x03\x42\r\x82\xb5\x18\ttimestamp\x12\x0e\n\x06siteId\x18\x02 \x01(\t\x12\x1c\n\nserverUUID\x18\x03 \x01(\tB\x08\x82\xb5\x18\x04uuid\x12\x13\n\x0bserverJobID\x18\x04 \x01(\x03\x12!\n\x0f\x63orrelationUUID\x18\x05 \x01(\tB\x08\x82\xb5\x18\x04uuid\x12\x19\n\x0emessageVersion\x18\x06 \x01(\x05:\x01\x31\x12\x16\n\x04uuid\x18\x07 \x01(\tB\x08\x82\xb5\x18\x04uuidBD\n\"com.ziften.server.protocol.messageB\x1e\x45xtensionCatalogRequestMessage')




_EXTENSIONCATALOGREQUEST = _descriptor.Descriptor(
  name='ExtensionCatalogRequest',
  full_name='ExtensionCatalogRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='ExtensionCatalogRequest.timeStamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')),
    _descriptor.FieldDescriptor(
      name='siteId', full_name='ExtensionCatalogRequest.siteId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serverUUID', full_name='ExtensionCatalogRequest.serverUUID', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='serverJobID', full_name='ExtensionCatalogRequest.serverJobID', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='correlationUUID', full_name='ExtensionCatalogRequest.correlationUUID', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='messageVersion', full_name='ExtensionCatalogRequest.messageVersion', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='ExtensionCatalogRequest.uuid', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=54,
  serialized_end=266,
)

DESCRIPTOR.message_types_by_name['ExtensionCatalogRequest'] = _EXTENSIONCATALOGREQUEST

class ExtensionCatalogRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXTENSIONCATALOGREQUEST

  # @@protoc_insertion_point(class_scope:ExtensionCatalogRequest)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\"com.ziften.server.protocol.messageB\036ExtensionCatalogRequestMessage')
_EXTENSIONCATALOGREQUEST.fields_by_name['timeStamp'].has_options = True
_EXTENSIONCATALOGREQUEST.fields_by_name['timeStamp']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')
_EXTENSIONCATALOGREQUEST.fields_by_name['serverUUID'].has_options = True
_EXTENSIONCATALOGREQUEST.fields_by_name['serverUUID']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
_EXTENSIONCATALOGREQUEST.fields_by_name['correlationUUID'].has_options = True
_EXTENSIONCATALOGREQUEST.fields_by_name['correlationUUID']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
_EXTENSIONCATALOGREQUEST.fields_by_name['uuid'].has_options = True
_EXTENSIONCATALOGREQUEST.fields_by_name['uuid']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
# @@protoc_insertion_point(module_scope)
