# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExtensionCommand.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import PostgresType_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ExtensionCommand.proto',
  package='',
  serialized_pb='\n\x16\x45xtensionCommand.proto\x1a\x12PostgresType.proto\"\xdb\x06\n\x10\x45xtensionCommand\x12 \n\ttimeStamp\x18\x01 \x01(\x03\x42\r\x82\xb5\x18\ttimestamp\x12\x0e\n\x06siteId\x18\x02 \x01(\t\x12\x16\n\x04uuid\x18\x03 \x01(\tB\x08\x82\xb5\x18\x04uuid\x12\x13\n\x0bserverJobID\x18\x04 \x01(\x03\x12!\n\x0f\x63orrelationUUID\x18\x05 \x01(\tB\x08\x82\xb5\x18\x04uuid\x12\x19\n\x0emessageVersion\x18\x06 \x01(\x05:\x01\x31\x12\x1f\n\rextensionUUID\x18\x07 \x01(\tB\x08\x82\xb5\x18\x04uuid\x12\x37\n\x07\x63ommand\x18\x08 \x01(\x0e\x32&.ExtensionCommand.ExtensionCommandType\x12\x36\n\rextensionType\x18\t \x01(\x0e\x32\x1f.ExtensionCommand.ExtensionType\x12\x17\n\x0f\x65xtensionObject\x18\n \x01(\x0c\x12\x1b\n\x13\x65xtensionParameters\x18\x0b \x03(\t\x12\x39\n\nrunHosting\x18\x0c \x01(\x0e\x32\x1c.ExtensionCommand.RunHosting:\x07Service\x12=\n\x0brunLifetime\x18\r \x01(\x0e\x32\x1d.ExtensionCommand.RunLifetime:\tEphemeral\x12*\n\x07runType\x18\x0e \x01(\x0e\x32\x19.ExtensionCommand.RunType\x12\x1a\n\x12runPeriodicallySec\x18\x0f \x01(\x05\"T\n\x14\x45xtensionCommandType\x12\x0b\n\x07Install\x10\x01\x12\n\n\x06Remove\x10\x02\x12\n\n\x06\x45nable\x10\x03\x12\x0b\n\x07\x44isable\x10\x04\x12\n\n\x06Update\x10\x05\"%\n\rExtensionType\x12\x14\n\x10PowerShellScript\x10\x01\"(\n\nRunHosting\x12\x0b\n\x07Service\x10\x01\x12\r\n\tUserProxy\x10\x02\",\n\x0bRunLifetime\x12\r\n\tEphemeral\x10\x01\x12\x0e\n\nPersistent\x10\x02\"K\n\x07RunType\x12\x08\n\x04Once\x10\x01\x12\n\n\x06OnBoot\x10\x02\x12\n\n\x06OnIdle\x10\x03\x12\x10\n\x0cPeriodically\x10\x04\x12\x0c\n\x08OnDemand\x10\x05\x42=\n\"com.ziften.server.protocol.messageB\x17\x45xtensionCommandMessage')



_EXTENSIONCOMMAND_EXTENSIONCOMMANDTYPE = _descriptor.EnumDescriptor(
  name='ExtensionCommandType',
  full_name='ExtensionCommand.ExtensionCommandType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Install', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Remove', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Enable', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Disable', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Update', index=4, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=618,
  serialized_end=702,
)

_EXTENSIONCOMMAND_EXTENSIONTYPE = _descriptor.EnumDescriptor(
  name='ExtensionType',
  full_name='ExtensionCommand.ExtensionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PowerShellScript', index=0, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=704,
  serialized_end=741,
)

_EXTENSIONCOMMAND_RUNHOSTING = _descriptor.EnumDescriptor(
  name='RunHosting',
  full_name='ExtensionCommand.RunHosting',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Service', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UserProxy', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=743,
  serialized_end=783,
)

_EXTENSIONCOMMAND_RUNLIFETIME = _descriptor.EnumDescriptor(
  name='RunLifetime',
  full_name='ExtensionCommand.RunLifetime',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Ephemeral', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Persistent', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=785,
  serialized_end=829,
)

_EXTENSIONCOMMAND_RUNTYPE = _descriptor.EnumDescriptor(
  name='RunType',
  full_name='ExtensionCommand.RunType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Once', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OnBoot', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OnIdle', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Periodically', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OnDemand', index=4, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=831,
  serialized_end=906,
)


_EXTENSIONCOMMAND = _descriptor.Descriptor(
  name='ExtensionCommand',
  full_name='ExtensionCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='ExtensionCommand.timeStamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')),
    _descriptor.FieldDescriptor(
      name='siteId', full_name='ExtensionCommand.siteId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='ExtensionCommand.uuid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='serverJobID', full_name='ExtensionCommand.serverJobID', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='correlationUUID', full_name='ExtensionCommand.correlationUUID', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='messageVersion', full_name='ExtensionCommand.messageVersion', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='extensionUUID', full_name='ExtensionCommand.extensionUUID', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='command', full_name='ExtensionCommand.command', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='extensionType', full_name='ExtensionCommand.extensionType', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='extensionObject', full_name='ExtensionCommand.extensionObject', index=9,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='extensionParameters', full_name='ExtensionCommand.extensionParameters', index=10,
      number=11, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='runHosting', full_name='ExtensionCommand.runHosting', index=11,
      number=12, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='runLifetime', full_name='ExtensionCommand.runLifetime', index=12,
      number=13, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='runType', full_name='ExtensionCommand.runType', index=13,
      number=14, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='runPeriodicallySec', full_name='ExtensionCommand.runPeriodicallySec', index=14,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EXTENSIONCOMMAND_EXTENSIONCOMMANDTYPE,
    _EXTENSIONCOMMAND_EXTENSIONTYPE,
    _EXTENSIONCOMMAND_RUNHOSTING,
    _EXTENSIONCOMMAND_RUNLIFETIME,
    _EXTENSIONCOMMAND_RUNTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=47,
  serialized_end=906,
)

_EXTENSIONCOMMAND.fields_by_name['command'].enum_type = _EXTENSIONCOMMAND_EXTENSIONCOMMANDTYPE
_EXTENSIONCOMMAND.fields_by_name['extensionType'].enum_type = _EXTENSIONCOMMAND_EXTENSIONTYPE
_EXTENSIONCOMMAND.fields_by_name['runHosting'].enum_type = _EXTENSIONCOMMAND_RUNHOSTING
_EXTENSIONCOMMAND.fields_by_name['runLifetime'].enum_type = _EXTENSIONCOMMAND_RUNLIFETIME
_EXTENSIONCOMMAND.fields_by_name['runType'].enum_type = _EXTENSIONCOMMAND_RUNTYPE
_EXTENSIONCOMMAND_EXTENSIONCOMMANDTYPE.containing_type = _EXTENSIONCOMMAND;
_EXTENSIONCOMMAND_EXTENSIONTYPE.containing_type = _EXTENSIONCOMMAND;
_EXTENSIONCOMMAND_RUNHOSTING.containing_type = _EXTENSIONCOMMAND;
_EXTENSIONCOMMAND_RUNLIFETIME.containing_type = _EXTENSIONCOMMAND;
_EXTENSIONCOMMAND_RUNTYPE.containing_type = _EXTENSIONCOMMAND;
DESCRIPTOR.message_types_by_name['ExtensionCommand'] = _EXTENSIONCOMMAND

class ExtensionCommand(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXTENSIONCOMMAND

  # @@protoc_insertion_point(class_scope:ExtensionCommand)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\"com.ziften.server.protocol.messageB\027ExtensionCommandMessage')
_EXTENSIONCOMMAND.fields_by_name['timeStamp'].has_options = True
_EXTENSIONCOMMAND.fields_by_name['timeStamp']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')
_EXTENSIONCOMMAND.fields_by_name['uuid'].has_options = True
_EXTENSIONCOMMAND.fields_by_name['uuid']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
_EXTENSIONCOMMAND.fields_by_name['correlationUUID'].has_options = True
_EXTENSIONCOMMAND.fields_by_name['correlationUUID']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
_EXTENSIONCOMMAND.fields_by_name['extensionUUID'].has_options = True
_EXTENSIONCOMMAND.fields_by_name['extensionUUID']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
# @@protoc_insertion_point(module_scope)
