# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExtensionCatalogResponse.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import PostgresType_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ExtensionCatalogResponse.proto',
  package='',
  serialized_pb='\n\x1e\x45xtensionCatalogResponse.proto\x1a\x12PostgresType.proto\"\x81\x06\n\x18\x45xtensionCatalogResponse\x12 \n\ttimeStamp\x18\x01 \x01(\x03\x42\r\x82\xb5\x18\ttimestamp\x12\x0e\n\x06siteId\x18\x02 \x01(\t\x12\x1c\n\nserverUUID\x18\x03 \x01(\tB\x08\x82\xb5\x18\x04uuid\x12\x13\n\x0bserverJobID\x18\x04 \x01(\x03\x12!\n\x0f\x63orrelationUUID\x18\x05 \x01(\tB\x08\x82\xb5\x18\x04uuid\x12\x1b\n\tagentGUID\x18\x06 \x01(\tB\x08\x82\xb5\x18\x04uuid\x12\x19\n\x0emessageVersion\x18\x07 \x01(\x05:\x01\x31\x12\x1f\n\rextensionUUID\x18\x08 \x01(\tB\x08\x82\xb5\x18\x04uuid\x12\x37\n\x05state\x18\t \x01(\x0e\x32(.ExtensionCatalogResponse.ExtensionState\x12\x1b\n\x13\x65xtensionParameters\x18\n \x03(\t\x12\x38\n\nrunHosting\x18\x0b \x01(\x0e\x32$.ExtensionCatalogResponse.RunHosting\x12:\n\x0brunLifetime\x18\x0c \x01(\x0e\x32%.ExtensionCatalogResponse.RunLifetime\x12\x32\n\x07runType\x18\r \x01(\x0e\x32!.ExtensionCatalogResponse.RunType\x12\x1a\n\x12runPeriodicallySec\x18\x0e \x01(\x05\x12\x16\n\x04uuid\x18\x0f \x01(\tB\x08\x82\xb5\x18\x04uuid\"+\n\x0e\x45xtensionState\x12\x0b\n\x07\x45nabled\x10\x01\x12\x0c\n\x08\x44isabled\x10\x02\"(\n\nRunHosting\x12\x0b\n\x07Service\x10\x01\x12\r\n\tUserProxy\x10\x02\",\n\x0bRunLifetime\x12\r\n\tEphemeral\x10\x01\x12\x0e\n\nPersistent\x10\x02\"K\n\x07RunType\x12\x08\n\x04Once\x10\x01\x12\n\n\x06OnBoot\x10\x02\x12\n\n\x06OnIdle\x10\x03\x12\x10\n\x0cPeriodically\x10\x04\x12\x0c\n\x08OnDemand\x10\x05\x42\x45\n\"com.ziften.server.protocol.messageB\x1f\x45xtensionCatalogResponseMessage')



_EXTENSIONCATALOGRESPONSE_EXTENSIONSTATE = _descriptor.EnumDescriptor(
  name='ExtensionState',
  full_name='ExtensionCatalogResponse.ExtensionState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Enabled', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Disabled', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=616,
  serialized_end=659,
)

_EXTENSIONCATALOGRESPONSE_RUNHOSTING = _descriptor.EnumDescriptor(
  name='RunHosting',
  full_name='ExtensionCatalogResponse.RunHosting',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Service', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UserProxy', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=661,
  serialized_end=701,
)

_EXTENSIONCATALOGRESPONSE_RUNLIFETIME = _descriptor.EnumDescriptor(
  name='RunLifetime',
  full_name='ExtensionCatalogResponse.RunLifetime',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Ephemeral', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Persistent', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=703,
  serialized_end=747,
)

_EXTENSIONCATALOGRESPONSE_RUNTYPE = _descriptor.EnumDescriptor(
  name='RunType',
  full_name='ExtensionCatalogResponse.RunType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Once', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OnBoot', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OnIdle', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Periodically', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OnDemand', index=4, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=749,
  serialized_end=824,
)


_EXTENSIONCATALOGRESPONSE = _descriptor.Descriptor(
  name='ExtensionCatalogResponse',
  full_name='ExtensionCatalogResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='ExtensionCatalogResponse.timeStamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')),
    _descriptor.FieldDescriptor(
      name='siteId', full_name='ExtensionCatalogResponse.siteId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serverUUID', full_name='ExtensionCatalogResponse.serverUUID', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='serverJobID', full_name='ExtensionCatalogResponse.serverJobID', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='correlationUUID', full_name='ExtensionCatalogResponse.correlationUUID', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='agentGUID', full_name='ExtensionCatalogResponse.agentGUID', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='messageVersion', full_name='ExtensionCatalogResponse.messageVersion', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='extensionUUID', full_name='ExtensionCatalogResponse.extensionUUID', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='state', full_name='ExtensionCatalogResponse.state', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='extensionParameters', full_name='ExtensionCatalogResponse.extensionParameters', index=9,
      number=10, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='runHosting', full_name='ExtensionCatalogResponse.runHosting', index=10,
      number=11, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='runLifetime', full_name='ExtensionCatalogResponse.runLifetime', index=11,
      number=12, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='runType', full_name='ExtensionCatalogResponse.runType', index=12,
      number=13, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='runPeriodicallySec', full_name='ExtensionCatalogResponse.runPeriodicallySec', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='ExtensionCatalogResponse.uuid', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EXTENSIONCATALOGRESPONSE_EXTENSIONSTATE,
    _EXTENSIONCATALOGRESPONSE_RUNHOSTING,
    _EXTENSIONCATALOGRESPONSE_RUNLIFETIME,
    _EXTENSIONCATALOGRESPONSE_RUNTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=55,
  serialized_end=824,
)

_EXTENSIONCATALOGRESPONSE.fields_by_name['state'].enum_type = _EXTENSIONCATALOGRESPONSE_EXTENSIONSTATE
_EXTENSIONCATALOGRESPONSE.fields_by_name['runHosting'].enum_type = _EXTENSIONCATALOGRESPONSE_RUNHOSTING
_EXTENSIONCATALOGRESPONSE.fields_by_name['runLifetime'].enum_type = _EXTENSIONCATALOGRESPONSE_RUNLIFETIME
_EXTENSIONCATALOGRESPONSE.fields_by_name['runType'].enum_type = _EXTENSIONCATALOGRESPONSE_RUNTYPE
_EXTENSIONCATALOGRESPONSE_EXTENSIONSTATE.containing_type = _EXTENSIONCATALOGRESPONSE;
_EXTENSIONCATALOGRESPONSE_RUNHOSTING.containing_type = _EXTENSIONCATALOGRESPONSE;
_EXTENSIONCATALOGRESPONSE_RUNLIFETIME.containing_type = _EXTENSIONCATALOGRESPONSE;
_EXTENSIONCATALOGRESPONSE_RUNTYPE.containing_type = _EXTENSIONCATALOGRESPONSE;
DESCRIPTOR.message_types_by_name['ExtensionCatalogResponse'] = _EXTENSIONCATALOGRESPONSE

class ExtensionCatalogResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXTENSIONCATALOGRESPONSE

  # @@protoc_insertion_point(class_scope:ExtensionCatalogResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\"com.ziften.server.protocol.messageB\037ExtensionCatalogResponseMessage')
_EXTENSIONCATALOGRESPONSE.fields_by_name['timeStamp'].has_options = True
_EXTENSIONCATALOGRESPONSE.fields_by_name['timeStamp']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')
_EXTENSIONCATALOGRESPONSE.fields_by_name['serverUUID'].has_options = True
_EXTENSIONCATALOGRESPONSE.fields_by_name['serverUUID']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
_EXTENSIONCATALOGRESPONSE.fields_by_name['correlationUUID'].has_options = True
_EXTENSIONCATALOGRESPONSE.fields_by_name['correlationUUID']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
_EXTENSIONCATALOGRESPONSE.fields_by_name['agentGUID'].has_options = True
_EXTENSIONCATALOGRESPONSE.fields_by_name['agentGUID']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
_EXTENSIONCATALOGRESPONSE.fields_by_name['extensionUUID'].has_options = True
_EXTENSIONCATALOGRESPONSE.fields_by_name['extensionUUID']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
_EXTENSIONCATALOGRESPONSE.fields_by_name['uuid'].has_options = True
_EXTENSIONCATALOGRESPONSE.fields_by_name['uuid']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
# @@protoc_insertion_point(module_scope)
