# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExtensionCommandResponse.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import PostgresType_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ExtensionCommandResponse.proto',
  package='',
  serialized_pb='\n\x1e\x45xtensionCommandResponse.proto\x1a\x12PostgresType.proto\"\x88\x06\n\x18\x45xtensionCommandResponse\x12 \n\ttimeStamp\x18\x01 \x01(\x03\x42\r\x82\xb5\x18\ttimestamp\x12\x0e\n\x06siteId\x18\x02 \x01(\t\x12\x1c\n\nserverUUID\x18\x03 \x01(\tB\x08\x82\xb5\x18\x04uuid\x12\x13\n\x0bserverJobID\x18\x04 \x01(\x03\x12!\n\x0f\x63orrelationUUID\x18\x05 \x01(\tB\x08\x82\xb5\x18\x04uuid\x12\x1b\n\tagentGUID\x18\x06 \x01(\tB\x08\x82\xb5\x18\x04uuid\x12\x19\n\x0emessageVersion\x18\x07 \x01(\x05:\x01\x31\x12\x1f\n\rextensionUUID\x18\x08 \x01(\tB\x08\x82\xb5\x18\x04uuid\x12?\n\x07\x63ommand\x18\t \x01(\x0e\x32..ExtensionCommandResponse.ExtensionCommandType\x12H\n\x06result\x18\n \x01(\x0e\x32\x38.ExtensionCommandResponse.ExtensionCommandResponseResult\x12\x15\n\rstrResultText\x18\x0b \x01(\t\x12\x16\n\x04uuid\x18\x0c \x01(\tB\x08\x82\xb5\x18\x04uuid\"T\n\x14\x45xtensionCommandType\x12\x0b\n\x07Install\x10\x01\x12\n\n\x06Remove\x10\x02\x12\n\n\x06\x45nable\x10\x03\x12\x0b\n\x07\x44isable\x10\x04\x12\n\n\x06Update\x10\x05\"\xfa\x01\n\x1e\x45xtensionCommandResponseResult\x12\x12\n\x0e\x45XTCMD_SUCCESS\x10\x00\x12\x12\n\x0e\x45XTCMD_FAILURE\x10\x01\x12#\n\x1f\x45XTCMD_FAIL_UNSUPPORTED_VERSION\x10\x02\x12\x15\n\x11\x45XTCMD_FAIL_TRUST\x10\x03\x12\x19\n\x15\x45XTCMD_FAIL_NOT_EXIST\x10\x04\x12\x1d\n\x19\x45XTCMD_FAIL_ALREADY_EXIST\x10\x05\x12\x18\n\x14\x45XTCMD_FAIL_DISABLED\x10\x06\x12 \n\x1c\x45XTCMD_FAIL_UNSUPPORTED_TYPE\x10\x07\x42\x45\n\"com.ziften.server.protocol.messageB\x1f\x45xtensionCommandResponseMessage')



_EXTENSIONCOMMANDRESPONSE_EXTENSIONCOMMANDTYPE = _descriptor.EnumDescriptor(
  name='ExtensionCommandType',
  full_name='ExtensionCommandResponse.ExtensionCommandType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Install', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Remove', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Enable', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Disable', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Update', index=4, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=494,
  serialized_end=578,
)

_EXTENSIONCOMMANDRESPONSE_EXTENSIONCOMMANDRESPONSERESULT = _descriptor.EnumDescriptor(
  name='ExtensionCommandResponseResult',
  full_name='ExtensionCommandResponse.ExtensionCommandResponseResult',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EXTCMD_SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXTCMD_FAILURE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXTCMD_FAIL_UNSUPPORTED_VERSION', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXTCMD_FAIL_TRUST', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXTCMD_FAIL_NOT_EXIST', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXTCMD_FAIL_ALREADY_EXIST', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXTCMD_FAIL_DISABLED', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXTCMD_FAIL_UNSUPPORTED_TYPE', index=7, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=581,
  serialized_end=831,
)


_EXTENSIONCOMMANDRESPONSE = _descriptor.Descriptor(
  name='ExtensionCommandResponse',
  full_name='ExtensionCommandResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='ExtensionCommandResponse.timeStamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')),
    _descriptor.FieldDescriptor(
      name='siteId', full_name='ExtensionCommandResponse.siteId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serverUUID', full_name='ExtensionCommandResponse.serverUUID', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='serverJobID', full_name='ExtensionCommandResponse.serverJobID', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='correlationUUID', full_name='ExtensionCommandResponse.correlationUUID', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='agentGUID', full_name='ExtensionCommandResponse.agentGUID', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='messageVersion', full_name='ExtensionCommandResponse.messageVersion', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='extensionUUID', full_name='ExtensionCommandResponse.extensionUUID', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='command', full_name='ExtensionCommandResponse.command', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result', full_name='ExtensionCommandResponse.result', index=9,
      number=10, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='strResultText', full_name='ExtensionCommandResponse.strResultText', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='ExtensionCommandResponse.uuid', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EXTENSIONCOMMANDRESPONSE_EXTENSIONCOMMANDTYPE,
    _EXTENSIONCOMMANDRESPONSE_EXTENSIONCOMMANDRESPONSERESULT,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=55,
  serialized_end=831,
)

_EXTENSIONCOMMANDRESPONSE.fields_by_name['command'].enum_type = _EXTENSIONCOMMANDRESPONSE_EXTENSIONCOMMANDTYPE
_EXTENSIONCOMMANDRESPONSE.fields_by_name['result'].enum_type = _EXTENSIONCOMMANDRESPONSE_EXTENSIONCOMMANDRESPONSERESULT
_EXTENSIONCOMMANDRESPONSE_EXTENSIONCOMMANDTYPE.containing_type = _EXTENSIONCOMMANDRESPONSE;
_EXTENSIONCOMMANDRESPONSE_EXTENSIONCOMMANDRESPONSERESULT.containing_type = _EXTENSIONCOMMANDRESPONSE;
DESCRIPTOR.message_types_by_name['ExtensionCommandResponse'] = _EXTENSIONCOMMANDRESPONSE

class ExtensionCommandResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXTENSIONCOMMANDRESPONSE

  # @@protoc_insertion_point(class_scope:ExtensionCommandResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\"com.ziften.server.protocol.messageB\037ExtensionCommandResponseMessage')
_EXTENSIONCOMMANDRESPONSE.fields_by_name['timeStamp'].has_options = True
_EXTENSIONCOMMANDRESPONSE.fields_by_name['timeStamp']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')
_EXTENSIONCOMMANDRESPONSE.fields_by_name['serverUUID'].has_options = True
_EXTENSIONCOMMANDRESPONSE.fields_by_name['serverUUID']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
_EXTENSIONCOMMANDRESPONSE.fields_by_name['correlationUUID'].has_options = True
_EXTENSIONCOMMANDRESPONSE.fields_by_name['correlationUUID']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
_EXTENSIONCOMMANDRESPONSE.fields_by_name['agentGUID'].has_options = True
_EXTENSIONCOMMANDRESPONSE.fields_by_name['agentGUID']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
_EXTENSIONCOMMANDRESPONSE.fields_by_name['extensionUUID'].has_options = True
_EXTENSIONCOMMANDRESPONSE.fields_by_name['extensionUUID']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
_EXTENSIONCOMMANDRESPONSE.fields_by_name['uuid'].has_options = True
_EXTENSIONCOMMANDRESPONSE.fields_by_name['uuid']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
# @@protoc_insertion_point(module_scope)
