# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExtensionRunResults.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import PostgresType_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ExtensionRunResults.proto',
  package='',
  serialized_pb='\n\x19\x45xtensionRunResults.proto\x1a\x12PostgresType.proto\"\xb6\x05\n\x13\x45xtensionRunResults\x12 \n\ttimeStamp\x18\x01 \x01(\x03\x42\r\x82\xb5\x18\ttimestamp\x12\x0e\n\x06siteId\x18\x02 \x01(\t\x12\x16\n\x04uuid\x18\x03 \x01(\tB\x08\x82\xb5\x18\x04uuid\x12\x13\n\x0bserverJobID\x18\x04 \x01(\x03\x12!\n\x0f\x63orrelationUUID\x18\x05 \x01(\tB\x08\x82\xb5\x18\x04uuid\x12\x1b\n\tagentGUID\x18\x06 \x01(\tB\x08\x82\xb5\x18\x04uuid\x12\x19\n\x0emessageVersion\x18\x07 \x01(\x05:\x01\x31\x12\x1f\n\rextensionUUID\x18\x08 \x01(\tB\x08\x82\xb5\x18\x04uuid\x12.\n\x17startExecutionTimeStamp\x18\t \x01(\x03\x42\r\x82\xb5\x18\ttimestamp\x12,\n\x15\x65ndExecutionTimeStamp\x18\n \x01(\x03\x42\r\x82\xb5\x18\ttimestamp\x12\r\n\x05seqNo\x18\x0b \x01(\x05\x12\x10\n\x08\x65xitCode\x18\x0c \x01(\x05\x12\x10\n\x08stdError\x18\r \x01(\t\x12\x11\n\teventCode\x18\x0e \x01(\x05\x12\x0c\n\x04tag0\x18\x0f \x01(\t\x12\x0c\n\x04tag1\x18\x10 \x01(\t\x12\x0c\n\x04tag2\x18\x11 \x01(\t\x12\x0c\n\x04tag3\x18\x12 \x01(\t\x12\x0c\n\x04tag4\x18\x13 \x01(\t\x12\x0c\n\x04tag5\x18\x14 \x01(\t\x12\x0c\n\x04tag6\x18\x15 \x01(\t\x12\x0c\n\x04tag7\x18\x16 \x01(\t\x12\x0c\n\x04tag8\x18\x17 \x01(\t\x12\x0c\n\x04tag9\x18\x18 \x01(\t\x12\r\n\x05tag10\x18\x19 \x01(\t\x12\r\n\x05tag11\x18\x1a \x01(\t\x12\r\n\x05tag12\x18\x1b \x01(\t\x12\r\n\x05tag13\x18\x1c \x01(\t\x12\r\n\x05tag14\x18\x1d \x01(\t\x12\r\n\x05tag15\x18\x1e \x01(\t\x12\r\n\x05tag16\x18\x1f \x01(\t\x12\r\n\x05tag17\x18  \x01(\t\x12\r\n\x05tag18\x18! \x01(\t\x12\r\n\x05tag19\x18\" \x01(\tB@\n\"com.ziften.server.protocol.messageB\x1a\x45xtensionRunResultsMessage')




_EXTENSIONRUNRESULTS = _descriptor.Descriptor(
  name='ExtensionRunResults',
  full_name='ExtensionRunResults',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='ExtensionRunResults.timeStamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')),
    _descriptor.FieldDescriptor(
      name='siteId', full_name='ExtensionRunResults.siteId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='ExtensionRunResults.uuid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='serverJobID', full_name='ExtensionRunResults.serverJobID', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='correlationUUID', full_name='ExtensionRunResults.correlationUUID', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='agentGUID', full_name='ExtensionRunResults.agentGUID', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='messageVersion', full_name='ExtensionRunResults.messageVersion', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='extensionUUID', full_name='ExtensionRunResults.extensionUUID', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='startExecutionTimeStamp', full_name='ExtensionRunResults.startExecutionTimeStamp', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')),
    _descriptor.FieldDescriptor(
      name='endExecutionTimeStamp', full_name='ExtensionRunResults.endExecutionTimeStamp', index=9,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')),
    _descriptor.FieldDescriptor(
      name='seqNo', full_name='ExtensionRunResults.seqNo', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exitCode', full_name='ExtensionRunResults.exitCode', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stdError', full_name='ExtensionRunResults.stdError', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eventCode', full_name='ExtensionRunResults.eventCode', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag0', full_name='ExtensionRunResults.tag0', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag1', full_name='ExtensionRunResults.tag1', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag2', full_name='ExtensionRunResults.tag2', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag3', full_name='ExtensionRunResults.tag3', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag4', full_name='ExtensionRunResults.tag4', index=18,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag5', full_name='ExtensionRunResults.tag5', index=19,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag6', full_name='ExtensionRunResults.tag6', index=20,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag7', full_name='ExtensionRunResults.tag7', index=21,
      number=22, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag8', full_name='ExtensionRunResults.tag8', index=22,
      number=23, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag9', full_name='ExtensionRunResults.tag9', index=23,
      number=24, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag10', full_name='ExtensionRunResults.tag10', index=24,
      number=25, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag11', full_name='ExtensionRunResults.tag11', index=25,
      number=26, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag12', full_name='ExtensionRunResults.tag12', index=26,
      number=27, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag13', full_name='ExtensionRunResults.tag13', index=27,
      number=28, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag14', full_name='ExtensionRunResults.tag14', index=28,
      number=29, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag15', full_name='ExtensionRunResults.tag15', index=29,
      number=30, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag16', full_name='ExtensionRunResults.tag16', index=30,
      number=31, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag17', full_name='ExtensionRunResults.tag17', index=31,
      number=32, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag18', full_name='ExtensionRunResults.tag18', index=32,
      number=33, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag19', full_name='ExtensionRunResults.tag19', index=33,
      number=34, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=50,
  serialized_end=744,
)

DESCRIPTOR.message_types_by_name['ExtensionRunResults'] = _EXTENSIONRUNRESULTS

class ExtensionRunResults(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXTENSIONRUNRESULTS

  # @@protoc_insertion_point(class_scope:ExtensionRunResults)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\"com.ziften.server.protocol.messageB\032ExtensionRunResultsMessage')
_EXTENSIONRUNRESULTS.fields_by_name['timeStamp'].has_options = True
_EXTENSIONRUNRESULTS.fields_by_name['timeStamp']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')
_EXTENSIONRUNRESULTS.fields_by_name['uuid'].has_options = True
_EXTENSIONRUNRESULTS.fields_by_name['uuid']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
_EXTENSIONRUNRESULTS.fields_by_name['correlationUUID'].has_options = True
_EXTENSIONRUNRESULTS.fields_by_name['correlationUUID']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
_EXTENSIONRUNRESULTS.fields_by_name['agentGUID'].has_options = True
_EXTENSIONRUNRESULTS.fields_by_name['agentGUID']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
_EXTENSIONRUNRESULTS.fields_by_name['extensionUUID'].has_options = True
_EXTENSIONRUNRESULTS.fields_by_name['extensionUUID']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
_EXTENSIONRUNRESULTS.fields_by_name['startExecutionTimeStamp'].has_options = True
_EXTENSIONRUNRESULTS.fields_by_name['startExecutionTimeStamp']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')
_EXTENSIONRUNRESULTS.fields_by_name['endExecutionTimeStamp'].has_options = True
_EXTENSIONRUNRESULTS.fields_by_name['endExecutionTimeStamp']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')
# @@protoc_insertion_point(module_scope)
