# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iOSDeviceInfo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = _descriptor.FileDescriptor(
  name='iOSDeviceInfo.proto',
  package='',
  serialized_pb='\n\x13iOSDeviceInfo.proto\x1a\x12PostgresType.proto\"\xdf\x03\n\riOSDeviceInfo\x12\x11\n\ttimestamp\x18\x01 \x02(\x03\x12\x11\n\tagentGUID\x18\x02 \x02(\t\x12\x12\n\ndeviceType\x18\x03 \x02(\t\x12\x10\n\x08\x64\x65viceId\x18\x04 \x02(\t\x12\x10\n\x08modelMPN\x18\x05 \x02(\t\x12\x12\n\ndeviceName\x18\x06 \x02(\t\x12\x10\n\x08hostname\x18\x07 \x02(\t\x12\x14\n\x0cserialNumber\x18\x08 \x02(\t\x12\x0c\n\x04IMEI\x18\t \x01(\t\x12\x13\n\x0b\x63\x61rrierName\x18\n \x01(\t\x12\x12\n\niOSVersion\x18\x0b \x02(\t\x12\x17\n\x0fiOSBuildVersion\x18\x0c \x02(\t\x12\x15\n\rfreeDiskSpace\x18\r \x02(\x02\x12\x15\n\rusedDiskSpace\x18\x0e \x02(\x02\x12\x14\n\x0cisJailbroken\x18\x0f \x02(\x05\x12 \n\x18isLocationServicesActive\x18\x10 \x02(\x05\x12\x1c\n\x14isAuthorizedToiCloud\x18\x11 \x02(\x05\x12\x13\n\x0bisVPNActive\x18\x12 \x02(\x05\x12\r\n\x05ICCID\x18\x13 \x02(\t\x12\x14\n\x0c\x64iskCapacity\x18\x14 \x02(\x02\x12\x0e\n\x06siteId\x18\x15 \x01(\t\x12\x16\n\x04uuid\x18\x16 \x01(\tB\x08\x82\xb5\x18\x04uuidB:\n\"com.ziften.server.protocol.messageB\x14iOSDeviceInfoMessage')




_IOSDEVICEINFO = _descriptor.Descriptor(
  name='iOSDeviceInfo',
  full_name='iOSDeviceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='iOSDeviceInfo.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='agentGUID', full_name='iOSDeviceInfo.agentGUID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deviceType', full_name='iOSDeviceInfo.deviceType', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deviceId', full_name='iOSDeviceInfo.deviceId', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='modelMPN', full_name='iOSDeviceInfo.modelMPN', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deviceName', full_name='iOSDeviceInfo.deviceName', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hostname', full_name='iOSDeviceInfo.hostname', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serialNumber', full_name='iOSDeviceInfo.serialNumber', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='IMEI', full_name='iOSDeviceInfo.IMEI', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='carrierName', full_name='iOSDeviceInfo.carrierName', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iOSVersion', full_name='iOSDeviceInfo.iOSVersion', index=10,
      number=11, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iOSBuildVersion', full_name='iOSDeviceInfo.iOSBuildVersion', index=11,
      number=12, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='freeDiskSpace', full_name='iOSDeviceInfo.freeDiskSpace', index=12,
      number=13, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='usedDiskSpace', full_name='iOSDeviceInfo.usedDiskSpace', index=13,
      number=14, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isJailbroken', full_name='iOSDeviceInfo.isJailbroken', index=14,
      number=15, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isLocationServicesActive', full_name='iOSDeviceInfo.isLocationServicesActive', index=15,
      number=16, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isAuthorizedToiCloud', full_name='iOSDeviceInfo.isAuthorizedToiCloud', index=16,
      number=17, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isVPNActive', full_name='iOSDeviceInfo.isVPNActive', index=17,
      number=18, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ICCID', full_name='iOSDeviceInfo.ICCID', index=18,
      number=19, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='diskCapacity', full_name='iOSDeviceInfo.diskCapacity', index=19,
      number=20, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='siteId', full_name='iOSDeviceInfo.siteId', index=20,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='iOSDeviceInfo.uuid', index=21,
      number=22, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=44,
  serialized_end=523,
)

DESCRIPTOR.message_types_by_name['iOSDeviceInfo'] = _IOSDEVICEINFO

class iOSDeviceInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _IOSDEVICEINFO

  # @@protoc_insertion_point(class_scope:iOSDeviceInfo)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\"com.ziften.server.protocol.messageB\024iOSDeviceInfoMessage')
_IOSDEVICEINFO.fields_by_name['uuid'].has_options = True
_IOSDEVICEINFO.fields_by_name['uuid']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
# @@protoc_insertion_point(module_scope)
