# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NetworkConnect.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import PostgresType_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='NetworkConnect.proto',
  package='',
  serialized_pb='\n\x14NetworkConnect.proto\x1a\x12PostgresType.proto\"\xd2\x04\n\x0eNetworkConnect\x12 \n\ttimeStamp\x18\x01 \x02(\x03\x42\r\x82\xb5\x18\ttimestamp\x12\x1b\n\tagentGUID\x18\x02 \x02(\tB\x08\x82\xb5\x18\x04uuid\x12\x37\n\x11IPAddressProtocol\x18\x03 \x02(\x0e\x32\x1c.NetworkConnect.ProtocolType\x12\x1b\n\tIPAddress\x18\x04 \x02(\x0c\x42\x08\x82\xb5\x18\x04inet\x12\x0b\n\x03PID\x18\x05 \x02(\x05\x12\x15\n\rimageFilepath\x18\x06 \x02(\t\x12\x14\n\x0cimageFileMD5\x18\x07 \x01(\t\x12\x13\n\x0b\x61\x63\x63ountName\x18\x08 \x01(\t\x12\x12\n\ndomainName\x18\t \x01(\t\x12\x0c\n\x04port\x18\n \x01(\x05\x12\x0e\n\x06siteId\x18\x0b \x01(\t\x12!\n\x0fIPSourceAddress\x18\x0c \x01(\x0c\x42\x08\x82\xb5\x18\x04inet\x12\x12\n\nsourcePort\x18\r \x01(\x05\x12\x38\n\x14\x63onnectionStreamType\x18\x0e \x01(\x0e\x32\x1a.NetworkConnect.StreamType\x12\x1c\n\x14\x63onnectionSuccessful\x18\x0f \x01(\x08\x12\x10\n\x08incoming\x18\x10 \x01(\x08\x12\x0f\n\x07version\x18\x11 \x01(\x05\x12\x10\n\x08hostname\x18\x12 \x01(\t\x12\x16\n\x04uuid\x18\x13 \x01(\tB\x08\x82\xb5\x18\x04uuid\".\n\x0cProtocolType\x12\x0e\n\nIPVersion4\x10\x00\x12\x0e\n\nIPVersion6\x10\x01\"\x1e\n\nStreamType\x12\x07\n\x03TCP\x10\x00\x12\x07\n\x03UDP\x10\x01\x42;\n\"com.ziften.server.protocol.messageB\x15NetworkConnectMessage')



_NETWORKCONNECT_PROTOCOLTYPE = _descriptor.EnumDescriptor(
  name='ProtocolType',
  full_name='NetworkConnect.ProtocolType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IPVersion4', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IPVersion6', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=561,
  serialized_end=607,
)

_NETWORKCONNECT_STREAMTYPE = _descriptor.EnumDescriptor(
  name='StreamType',
  full_name='NetworkConnect.StreamType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TCP', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UDP', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=609,
  serialized_end=639,
)


_NETWORKCONNECT = _descriptor.Descriptor(
  name='NetworkConnect',
  full_name='NetworkConnect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='NetworkConnect.timeStamp', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')),
    _descriptor.FieldDescriptor(
      name='agentGUID', full_name='NetworkConnect.agentGUID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='IPAddressProtocol', full_name='NetworkConnect.IPAddressProtocol', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='IPAddress', full_name='NetworkConnect.IPAddress', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004inet')),
    _descriptor.FieldDescriptor(
      name='PID', full_name='NetworkConnect.PID', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='imageFilepath', full_name='NetworkConnect.imageFilepath', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='imageFileMD5', full_name='NetworkConnect.imageFileMD5', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accountName', full_name='NetworkConnect.accountName', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='domainName', full_name='NetworkConnect.domainName', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='NetworkConnect.port', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='siteId', full_name='NetworkConnect.siteId', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='IPSourceAddress', full_name='NetworkConnect.IPSourceAddress', index=11,
      number=12, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004inet')),
    _descriptor.FieldDescriptor(
      name='sourcePort', full_name='NetworkConnect.sourcePort', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='connectionStreamType', full_name='NetworkConnect.connectionStreamType', index=13,
      number=14, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='connectionSuccessful', full_name='NetworkConnect.connectionSuccessful', index=14,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='incoming', full_name='NetworkConnect.incoming', index=15,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='NetworkConnect.version', index=16,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hostname', full_name='NetworkConnect.hostname', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='NetworkConnect.uuid', index=18,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NETWORKCONNECT_PROTOCOLTYPE,
    _NETWORKCONNECT_STREAMTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=45,
  serialized_end=639,
)

_NETWORKCONNECT.fields_by_name['IPAddressProtocol'].enum_type = _NETWORKCONNECT_PROTOCOLTYPE
_NETWORKCONNECT.fields_by_name['connectionStreamType'].enum_type = _NETWORKCONNECT_STREAMTYPE
_NETWORKCONNECT_PROTOCOLTYPE.containing_type = _NETWORKCONNECT;
_NETWORKCONNECT_STREAMTYPE.containing_type = _NETWORKCONNECT;
DESCRIPTOR.message_types_by_name['NetworkConnect'] = _NETWORKCONNECT

class NetworkConnect(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NETWORKCONNECT

  # @@protoc_insertion_point(class_scope:NetworkConnect)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\"com.ziften.server.protocol.messageB\025NetworkConnectMessage')
_NETWORKCONNECT.fields_by_name['timeStamp'].has_options = True
_NETWORKCONNECT.fields_by_name['timeStamp']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')
_NETWORKCONNECT.fields_by_name['agentGUID'].has_options = True
_NETWORKCONNECT.fields_by_name['agentGUID']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
_NETWORKCONNECT.fields_by_name['IPAddress'].has_options = True
_NETWORKCONNECT.fields_by_name['IPAddress']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004inet')
_NETWORKCONNECT.fields_by_name['IPSourceAddress'].has_options = True
_NETWORKCONNECT.fields_by_name['IPSourceAddress']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004inet')
_NETWORKCONNECT.fields_by_name['uuid'].has_options = True
_NETWORKCONNECT.fields_by_name['uuid']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
# @@protoc_insertion_point(module_scope)
