# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NetworkDataPID.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import PostgresType_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='NetworkDataPID.proto',
  package='',
  serialized_pb='\n\x14NetworkDataPID.proto\x1a\x12PostgresType.proto\"\xaa\x02\n\x0eNetworkDataPID\x12 \n\ttimeStamp\x18\x01 \x02(\x03\x42\r\x82\xb5\x18\ttimestamp\x12\x1b\n\tagentGUID\x18\x02 \x02(\tB\x08\x82\xb5\x18\x04uuid\x12\x0b\n\x03PID\x18\x03 \x02(\x05\x12\x15\n\rimageFilepath\x18\x04 \x02(\t\x12\x11\n\tsentBytes\x18\x05 \x02(\x05\x12\x15\n\rreceivedBytes\x18\x06 \x02(\x05\x12\x14\n\x0csentBytes_v2\x18\t \x01(\x04\x12\x18\n\x10receivedBytes_v2\x18\n \x01(\x04\x12\x14\n\x0cimageFileMD5\x18\x07 \x01(\t\x12\x0e\n\x06siteId\x18\x08 \x01(\t\x12\x16\n\x04uuid\x18\x0b \x01(\tB\x08\x82\xb5\x18\x04uuid\x12\x1d\n\x0bprocessUUID\x18\x0c \x01(\tB\x08\x82\xb5\x18\x04uuidB;\n\"com.ziften.server.protocol.messageB\x15NetworkDataPIDMessage')




_NETWORKDATAPID = _descriptor.Descriptor(
  name='NetworkDataPID',
  full_name='NetworkDataPID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='NetworkDataPID.timeStamp', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')),
    _descriptor.FieldDescriptor(
      name='agentGUID', full_name='NetworkDataPID.agentGUID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='PID', full_name='NetworkDataPID.PID', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='imageFilepath', full_name='NetworkDataPID.imageFilepath', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sentBytes', full_name='NetworkDataPID.sentBytes', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='receivedBytes', full_name='NetworkDataPID.receivedBytes', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sentBytes_v2', full_name='NetworkDataPID.sentBytes_v2', index=6,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='receivedBytes_v2', full_name='NetworkDataPID.receivedBytes_v2', index=7,
      number=10, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='imageFileMD5', full_name='NetworkDataPID.imageFileMD5', index=8,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='siteId', full_name='NetworkDataPID.siteId', index=9,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='NetworkDataPID.uuid', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='processUUID', full_name='NetworkDataPID.processUUID', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=45,
  serialized_end=343,
)

DESCRIPTOR.message_types_by_name['NetworkDataPID'] = _NETWORKDATAPID

class NetworkDataPID(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NETWORKDATAPID

  # @@protoc_insertion_point(class_scope:NetworkDataPID)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\"com.ziften.server.protocol.messageB\025NetworkDataPIDMessage')
_NETWORKDATAPID.fields_by_name['timeStamp'].has_options = True
_NETWORKDATAPID.fields_by_name['timeStamp']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')
_NETWORKDATAPID.fields_by_name['agentGUID'].has_options = True
_NETWORKDATAPID.fields_by_name['agentGUID']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
_NETWORKDATAPID.fields_by_name['uuid'].has_options = True
_NETWORKDATAPID.fields_by_name['uuid']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
_NETWORKDATAPID.fields_by_name['processUUID'].has_options = True
_NETWORKDATAPID.fields_by_name['processUUID']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
# @@protoc_insertion_point(module_scope)
