# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OSXAgentStatus.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = _descriptor.FileDescriptor(
  name='OSXAgentStatus.proto',
  package='',
  serialized_pb='\n\x14OSXAgentStatus.proto\x1a\x12PostgresType.proto\"\xc7\x02\n\x0eOSXAgentStatus\x12 \n\ttimeStamp\x18\x01 \x02(\x03\x42\r\x82\xb5\x18\ttimestamp\x12\x1b\n\tagentGUID\x18\x02 \x02(\tB\x08\x82\xb5\x18\x04uuid\x12;\n\x0b\x61gentStatus\x18\x03 \x02(\x0e\x32&.OSXAgentStatus.AgentStatusMessageType\x12\x14\n\x0coldAgentGUID\x18\x08 \x01(\t\x12\x0e\n\x06siteId\x18\t \x01(\t\x12\x14\n\x0c\x63omputerName\x18\n \x01(\t\x12\x16\n\x04uuid\x18\x0b \x01(\tB\x08\x82\xb5\x18\x04uuid\"e\n\x16\x41gentStatusMessageType\x12\x10\n\x0c\x41GENTSTARTED\x10\x00\x12\x10\n\x0c\x41GENTSTOPPED\x10\x01\x12\x13\n\x0f\x41GENTGUIDCHANGE\x10\x05\x12\x12\n\x0e\x41GENTHEARTBEAT\x10\x06\x42;\n\"com.ziften.server.protocol.messageB\x15OSXAgentStatusMessage')



_OSXAGENTSTATUS_AGENTSTATUSMESSAGETYPE = _descriptor.EnumDescriptor(
  name='AgentStatusMessageType',
  full_name='OSXAgentStatus.AgentStatusMessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AGENTSTARTED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AGENTSTOPPED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AGENTGUIDCHANGE', index=2, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AGENTHEARTBEAT', index=3, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=271,
  serialized_end=372,
)


_OSXAGENTSTATUS = _descriptor.Descriptor(
  name='OSXAgentStatus',
  full_name='OSXAgentStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='OSXAgentStatus.timeStamp', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')),
    _descriptor.FieldDescriptor(
      name='agentGUID', full_name='OSXAgentStatus.agentGUID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='agentStatus', full_name='OSXAgentStatus.agentStatus', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='oldAgentGUID', full_name='OSXAgentStatus.oldAgentGUID', index=3,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='siteId', full_name='OSXAgentStatus.siteId', index=4,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='computerName', full_name='OSXAgentStatus.computerName', index=5,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='OSXAgentStatus.uuid', index=6,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _OSXAGENTSTATUS_AGENTSTATUSMESSAGETYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=45,
  serialized_end=372,
)

_OSXAGENTSTATUS.fields_by_name['agentStatus'].enum_type = _OSXAGENTSTATUS_AGENTSTATUSMESSAGETYPE
_OSXAGENTSTATUS_AGENTSTATUSMESSAGETYPE.containing_type = _OSXAGENTSTATUS;
DESCRIPTOR.message_types_by_name['OSXAgentStatus'] = _OSXAGENTSTATUS

class OSXAgentStatus(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _OSXAGENTSTATUS

  # @@protoc_insertion_point(class_scope:OSXAgentStatus)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\"com.ziften.server.protocol.messageB\025OSXAgentStatusMessage')
_OSXAGENTSTATUS.fields_by_name['timeStamp'].has_options = True
_OSXAGENTSTATUS.fields_by_name['timeStamp']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')
_OSXAGENTSTATUS.fields_by_name['agentGUID'].has_options = True
_OSXAGENTSTATUS.fields_by_name['agentGUID']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
_OSXAGENTSTATUS.fields_by_name['uuid'].has_options = True
_OSXAGENTSTATUS.fields_by_name['uuid']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
# @@protoc_insertion_point(module_scope)
