# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OSXEventLogRecord.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = _descriptor.FileDescriptor(
  name='OSXEventLogRecord.proto',
  package='',
  serialized_pb='\n\x17OSXEventLogRecord.proto\x1a\x12PostgresType.proto\"\xfc\x02\n\x11OSXEventLogRecord\x12 \n\ttimeStamp\x18\x01 \x02(\x03\x42\r\x82\xb5\x18\ttimestamp\x12\x1b\n\tagentGUID\x18\x02 \x02(\tB\x08\x82\xb5\x18\x04uuid\x12\x15\n\rtimeGenerated\x18\x03 \x02(\x03\x12\x15\n\rimageFilename\x18\x04 \x02(\t\x12\x15\n\rimageFilepath\x18\x05 \x01(\t\x12/\n\teventType\x18\x06 \x02(\x0e\x32\x1c.OSXEventLogRecord.EventType\x12\x0e\n\x06siteId\x18\x07 \x01(\t\x12\x14\n\x0cimageFileMD5\x18\x08 \x01(\t\x12\x10\n\x08isDeamon\x18\t \x01(\x05\x12\x16\n\x04uuid\x18\n \x01(\tB\x08\x82\xb5\x18\x04uuid\"b\n\tEventType\x12\x18\n\x14\x45VENT_TYPE_APP_CRASH\x10\x00\x12\x17\n\x13\x45VENT_TYPE_APP_HANG\x10\x01\x12\"\n\x1e\x45VENT_TYPE_SYSTEM_KERNEL_PANIC\x10\x02\x42>\n\"com.ziften.server.protocol.messageB\x18OSXEventLogRecordMessage')



_OSXEVENTLOGRECORD_EVENTTYPE = _descriptor.EnumDescriptor(
  name='EventType',
  full_name='OSXEventLogRecord.EventType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EVENT_TYPE_APP_CRASH', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EVENT_TYPE_APP_HANG', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EVENT_TYPE_SYSTEM_KERNEL_PANIC', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=330,
  serialized_end=428,
)


_OSXEVENTLOGRECORD = _descriptor.Descriptor(
  name='OSXEventLogRecord',
  full_name='OSXEventLogRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='OSXEventLogRecord.timeStamp', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')),
    _descriptor.FieldDescriptor(
      name='agentGUID', full_name='OSXEventLogRecord.agentGUID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='timeGenerated', full_name='OSXEventLogRecord.timeGenerated', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='imageFilename', full_name='OSXEventLogRecord.imageFilename', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='imageFilepath', full_name='OSXEventLogRecord.imageFilepath', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eventType', full_name='OSXEventLogRecord.eventType', index=5,
      number=6, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='siteId', full_name='OSXEventLogRecord.siteId', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='imageFileMD5', full_name='OSXEventLogRecord.imageFileMD5', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isDeamon', full_name='OSXEventLogRecord.isDeamon', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='OSXEventLogRecord.uuid', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _OSXEVENTLOGRECORD_EVENTTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=48,
  serialized_end=428,
)

_OSXEVENTLOGRECORD.fields_by_name['eventType'].enum_type = _OSXEVENTLOGRECORD_EVENTTYPE
_OSXEVENTLOGRECORD_EVENTTYPE.containing_type = _OSXEVENTLOGRECORD;
DESCRIPTOR.message_types_by_name['OSXEventLogRecord'] = _OSXEVENTLOGRECORD

class OSXEventLogRecord(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _OSXEVENTLOGRECORD

  # @@protoc_insertion_point(class_scope:OSXEventLogRecord)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\"com.ziften.server.protocol.messageB\030OSXEventLogRecordMessage')
_OSXEVENTLOGRECORD.fields_by_name['timeStamp'].has_options = True
_OSXEVENTLOGRECORD.fields_by_name['timeStamp']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')
_OSXEVENTLOGRECORD.fields_by_name['agentGUID'].has_options = True
_OSXEVENTLOGRECORD.fields_by_name['agentGUID']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
_OSXEVENTLOGRECORD.fields_by_name['uuid'].has_options = True
_OSXEVENTLOGRECORD.fields_by_name['uuid']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
# @@protoc_insertion_point(module_scope)
