# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OSXNetworkConnect.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = _descriptor.FileDescriptor(
  name='OSXNetworkConnect.proto',
  package='',
  serialized_pb='\n\x17OSXNetworkConnect.proto\x1a\x12PostgresType.proto\"\xdb\x04\n\x11OSXNetworkConnect\x12 \n\ttimeStamp\x18\x01 \x02(\x03\x42\r\x82\xb5\x18\ttimestamp\x12\x1b\n\tagentGUID\x18\x02 \x02(\tB\x08\x82\xb5\x18\x04uuid\x12:\n\x11IPAddressProtocol\x18\x03 \x02(\x0e\x32\x1f.OSXNetworkConnect.ProtocolType\x12\x1b\n\tIPAddress\x18\x04 \x02(\x0c\x42\x08\x82\xb5\x18\x04inet\x12\x0b\n\x03PID\x18\x05 \x02(\x05\x12\x15\n\rimageFilepath\x18\x06 \x02(\t\x12\x14\n\x0cimageFileMD5\x18\x07 \x01(\t\x12\x13\n\x0b\x61\x63\x63ountName\x18\x08 \x01(\t\x12\x12\n\ndomainName\x18\t \x01(\t\x12\x0c\n\x04port\x18\n \x01(\x05\x12\x0e\n\x06siteId\x18\x0b \x01(\t\x12!\n\x0fIPSourceAddress\x18\x0c \x01(\x0c\x42\x08\x82\xb5\x18\x04inet\x12\x12\n\nsourcePort\x18\r \x01(\x05\x12;\n\x14\x63onnectionStreamType\x18\x0e \x01(\x0e\x32\x1d.OSXNetworkConnect.StreamType\x12\x1c\n\x14\x63onnectionSuccessful\x18\x0f \x01(\x08\x12\x10\n\x08incoming\x18\x10 \x01(\x08\x12\x0f\n\x07version\x18\x11 \x01(\x05\x12\x16\n\x04uuid\x18\x12 \x01(\tB\x08\x82\xb5\x18\x04uuid\x12\x10\n\x08hostname\x18\x13 \x01(\t\".\n\x0cProtocolType\x12\x0e\n\nIPVersion4\x10\x00\x12\x0e\n\nIPVersion6\x10\x01\"\x1e\n\nStreamType\x12\x07\n\x03TCP\x10\x00\x12\x07\n\x03UDP\x10\x01\x42>\n\"com.ziften.server.protocol.messageB\x18OSXNetworkConnectMessage')



_OSXNETWORKCONNECT_PROTOCOLTYPE = _descriptor.EnumDescriptor(
  name='ProtocolType',
  full_name='OSXNetworkConnect.ProtocolType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IPVersion4', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IPVersion6', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=573,
  serialized_end=619,
)

_OSXNETWORKCONNECT_STREAMTYPE = _descriptor.EnumDescriptor(
  name='StreamType',
  full_name='OSXNetworkConnect.StreamType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TCP', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UDP', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=621,
  serialized_end=651,
)


_OSXNETWORKCONNECT = _descriptor.Descriptor(
  name='OSXNetworkConnect',
  full_name='OSXNetworkConnect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='OSXNetworkConnect.timeStamp', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')),
    _descriptor.FieldDescriptor(
      name='agentGUID', full_name='OSXNetworkConnect.agentGUID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='IPAddressProtocol', full_name='OSXNetworkConnect.IPAddressProtocol', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='IPAddress', full_name='OSXNetworkConnect.IPAddress', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004inet')),
    _descriptor.FieldDescriptor(
      name='PID', full_name='OSXNetworkConnect.PID', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='imageFilepath', full_name='OSXNetworkConnect.imageFilepath', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='imageFileMD5', full_name='OSXNetworkConnect.imageFileMD5', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accountName', full_name='OSXNetworkConnect.accountName', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='domainName', full_name='OSXNetworkConnect.domainName', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='OSXNetworkConnect.port', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='siteId', full_name='OSXNetworkConnect.siteId', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='IPSourceAddress', full_name='OSXNetworkConnect.IPSourceAddress', index=11,
      number=12, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004inet')),
    _descriptor.FieldDescriptor(
      name='sourcePort', full_name='OSXNetworkConnect.sourcePort', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='connectionStreamType', full_name='OSXNetworkConnect.connectionStreamType', index=13,
      number=14, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='connectionSuccessful', full_name='OSXNetworkConnect.connectionSuccessful', index=14,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='incoming', full_name='OSXNetworkConnect.incoming', index=15,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='OSXNetworkConnect.version', index=16,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='OSXNetworkConnect.uuid', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='hostname', full_name='OSXNetworkConnect.hostname', index=18,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _OSXNETWORKCONNECT_PROTOCOLTYPE,
    _OSXNETWORKCONNECT_STREAMTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=48,
  serialized_end=651,
)

_OSXNETWORKCONNECT.fields_by_name['IPAddressProtocol'].enum_type = _OSXNETWORKCONNECT_PROTOCOLTYPE
_OSXNETWORKCONNECT.fields_by_name['connectionStreamType'].enum_type = _OSXNETWORKCONNECT_STREAMTYPE
_OSXNETWORKCONNECT_PROTOCOLTYPE.containing_type = _OSXNETWORKCONNECT;
_OSXNETWORKCONNECT_STREAMTYPE.containing_type = _OSXNETWORKCONNECT;
DESCRIPTOR.message_types_by_name['OSXNetworkConnect'] = _OSXNETWORKCONNECT

class OSXNetworkConnect(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _OSXNETWORKCONNECT

  # @@protoc_insertion_point(class_scope:OSXNetworkConnect)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\"com.ziften.server.protocol.messageB\030OSXNetworkConnectMessage')
_OSXNETWORKCONNECT.fields_by_name['timeStamp'].has_options = True
_OSXNETWORKCONNECT.fields_by_name['timeStamp']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')
_OSXNETWORKCONNECT.fields_by_name['agentGUID'].has_options = True
_OSXNETWORKCONNECT.fields_by_name['agentGUID']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
_OSXNETWORKCONNECT.fields_by_name['IPAddress'].has_options = True
_OSXNETWORKCONNECT.fields_by_name['IPAddress']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004inet')
_OSXNETWORKCONNECT.fields_by_name['IPSourceAddress'].has_options = True
_OSXNETWORKCONNECT.fields_by_name['IPSourceAddress']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004inet')
_OSXNETWORKCONNECT.fields_by_name['uuid'].has_options = True
_OSXNETWORKCONNECT.fields_by_name['uuid']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
# @@protoc_insertion_point(module_scope)
