# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OSXProcessInventory.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = _descriptor.FileDescriptor(
  name='OSXProcessInventory.proto',
  package='',
  serialized_pb='\n\x19OSXProcessInventory.proto\x1a\x12PostgresType.proto\"\xd8\x02\n\x13OSXProcessInventory\x12 \n\ttimeStamp\x18\x01 \x02(\x03\x42\r\x82\xb5\x18\ttimestamp\x12\x1b\n\tagentGuid\x18\x02 \x02(\tB\x08\x82\xb5\x18\x04uuid\x12\x0b\n\x03pid\x18\x03 \x02(\x05\x12\x10\n\x08\x66ullpath\x18\x04 \x02(\t\x12\x1a\n\x12runningProcessName\x18\x05 \x02(\t\x12\x12\n\nvirtualMem\x18\x06 \x02(\x03\x12\x13\n\x0bphysicalMem\x18\x07 \x02(\x03\x12\x10\n\x08userTime\x18\x08 \x02(\x03\x12\x12\n\nsystemTime\x18\t \x02(\x03\x12\x14\n\x0ctotalThreads\x18\n \x02(\x05\x12\x16\n\x0erunningThreads\x18\x0b \x02(\x05\x12\x10\n\x08priority\x18\x0c \x02(\x05\x12\x10\n\x08userName\x18\r \x01(\t\x12\x0e\n\x06siteId\x18\x0e \x01(\t\x12\x16\n\x04uuid\x18\x0f \x01(\tB\x08\x82\xb5\x18\x04uuidB@\n\"com.ziften.server.protocol.messageB\x1aOSXProcessInventoryMessage')




_OSXPROCESSINVENTORY = _descriptor.Descriptor(
  name='OSXProcessInventory',
  full_name='OSXProcessInventory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='OSXProcessInventory.timeStamp', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')),
    _descriptor.FieldDescriptor(
      name='agentGuid', full_name='OSXProcessInventory.agentGuid', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='pid', full_name='OSXProcessInventory.pid', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fullpath', full_name='OSXProcessInventory.fullpath', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='runningProcessName', full_name='OSXProcessInventory.runningProcessName', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='virtualMem', full_name='OSXProcessInventory.virtualMem', index=5,
      number=6, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='physicalMem', full_name='OSXProcessInventory.physicalMem', index=6,
      number=7, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='userTime', full_name='OSXProcessInventory.userTime', index=7,
      number=8, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='systemTime', full_name='OSXProcessInventory.systemTime', index=8,
      number=9, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='totalThreads', full_name='OSXProcessInventory.totalThreads', index=9,
      number=10, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='runningThreads', full_name='OSXProcessInventory.runningThreads', index=10,
      number=11, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='priority', full_name='OSXProcessInventory.priority', index=11,
      number=12, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='userName', full_name='OSXProcessInventory.userName', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='siteId', full_name='OSXProcessInventory.siteId', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='OSXProcessInventory.uuid', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=50,
  serialized_end=394,
)

DESCRIPTOR.message_types_by_name['OSXProcessInventory'] = _OSXPROCESSINVENTORY

class OSXProcessInventory(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _OSXPROCESSINVENTORY

  # @@protoc_insertion_point(class_scope:OSXProcessInventory)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\"com.ziften.server.protocol.messageB\032OSXProcessInventoryMessage')
_OSXPROCESSINVENTORY.fields_by_name['timeStamp'].has_options = True
_OSXPROCESSINVENTORY.fields_by_name['timeStamp']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')
_OSXPROCESSINVENTORY.fields_by_name['agentGuid'].has_options = True
_OSXPROCESSINVENTORY.fields_by_name['agentGuid']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
_OSXPROCESSINVENTORY.fields_by_name['uuid'].has_options = True
_OSXPROCESSINVENTORY.fields_by_name['uuid']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
# @@protoc_insertion_point(module_scope)
