# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PolicyStatus.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PolicyStatus.proto',
  package='',
  serialized_pb='\n\x12PolicyStatus.proto\x1a\x12PostgresType.proto\"\x9c\x04\n\x0cPolicyStatus\x12 \n\ttimeStamp\x18\x01 \x02(\x03\x42\r\x82\xb5\x18\ttimestamp\x12\x1b\n\tagentGUID\x18\x02 \x02(\tB\x08\x82\xb5\x18\x04uuid\x12\x1a\n\x12policiesIdentifier\x18\x03 \x02(\x03\x12\x10\n\x08policyID\x18\x04 \x02(\x04\x12Q\n\x0cpolicyStatus\x18\x05 \x01(\x0e\x32%.PolicyStatus.PolicyStatusMessageType:\x14UNUSED_POLICY_STATUS\x12\x10\n\x08\x66ilename\x18\x06 \x01(\t\x12\x15\n\rimagefilepath\x18\x07 \x01(\t\x12\x14\n\x0cimageFileMD5\x18\x08 \x01(\t\x12\x0e\n\x06\x64\x61taID\x18\t \x01(\x04\x12\x0e\n\x06siteId\x18\n \x01(\t\x12\x16\n\x04uuid\x18\x0b \x01(\tB\x08\x82\xb5\x18\x04uuid\x12\x0e\n\x06method\x18\x0c \x01(\t\"\xc4\x01\n\x17PolicyStatusMessageType\x12\x18\n\x14UNUSED_POLICY_STATUS\x10\x00\x12\x18\n\x14\x45XE_TRACKING_STARTED\x10\x01\x12\x18\n\x14\x45XE_TRACKING_STOPPED\x10\x02\x12\x15\n\x11\x45XE_IN_COMPLIANCE\x10\x03\x12\x19\n\x15\x45XE_OUT_OF_COMPLIANCE\x10\x04\x12\x12\n\x0e\x45XE_IS_RUNNING\x10\x05\x12\x15\n\x11\x45XE_ISNOT_RUNNING\x10\x06\x42\x39\n\"com.ziften.server.protocol.messageB\x13PolicyStatusMessage')



_POLICYSTATUS_POLICYSTATUSMESSAGETYPE = _descriptor.EnumDescriptor(
  name='PolicyStatusMessageType',
  full_name='PolicyStatus.PolicyStatusMessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNUSED_POLICY_STATUS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXE_TRACKING_STARTED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXE_TRACKING_STOPPED', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXE_IN_COMPLIANCE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXE_OUT_OF_COMPLIANCE', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXE_IS_RUNNING', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXE_ISNOT_RUNNING', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=387,
  serialized_end=583,
)


_POLICYSTATUS = _descriptor.Descriptor(
  name='PolicyStatus',
  full_name='PolicyStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='PolicyStatus.timeStamp', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')),
    _descriptor.FieldDescriptor(
      name='agentGUID', full_name='PolicyStatus.agentGUID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='policiesIdentifier', full_name='PolicyStatus.policiesIdentifier', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='policyID', full_name='PolicyStatus.policyID', index=3,
      number=4, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='policyStatus', full_name='PolicyStatus.policyStatus', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='filename', full_name='PolicyStatus.filename', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='imagefilepath', full_name='PolicyStatus.imagefilepath', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='imageFileMD5', full_name='PolicyStatus.imageFileMD5', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dataID', full_name='PolicyStatus.dataID', index=8,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='siteId', full_name='PolicyStatus.siteId', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='PolicyStatus.uuid', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='method', full_name='PolicyStatus.method', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _POLICYSTATUS_POLICYSTATUSMESSAGETYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=43,
  serialized_end=583,
)

_POLICYSTATUS.fields_by_name['policyStatus'].enum_type = _POLICYSTATUS_POLICYSTATUSMESSAGETYPE
_POLICYSTATUS_POLICYSTATUSMESSAGETYPE.containing_type = _POLICYSTATUS;
DESCRIPTOR.message_types_by_name['PolicyStatus'] = _POLICYSTATUS

class PolicyStatus(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _POLICYSTATUS

  # @@protoc_insertion_point(class_scope:PolicyStatus)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\"com.ziften.server.protocol.messageB\023PolicyStatusMessage')
_POLICYSTATUS.fields_by_name['timeStamp'].has_options = True
_POLICYSTATUS.fields_by_name['timeStamp']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')
_POLICYSTATUS.fields_by_name['agentGUID'].has_options = True
_POLICYSTATUS.fields_by_name['agentGUID']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
_POLICYSTATUS.fields_by_name['uuid'].has_options = True
_POLICYSTATUS.fields_by_name['uuid']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
# @@protoc_insertion_point(module_scope)
