# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Policy.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import PostgresType_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Policy.proto',
  package='',
  serialized_pb='\n\x0cPolicy.proto\x1a\x12PostgresType.proto\"\xd6\x05\n\x06Policy\x12\x13\n\x08policyID\x18\x01 \x01(\x05:\x01\x30\x12\x35\n\x08runFlags\x18\x02 \x01(\x0e\x32\x13.Policy.RunRuleFlag:\x0eRUN_RULE_TIMER\x12\"\n\x06method\x18\x03 \x01(\t:\x12\x43HECK_PROCESS_LIST\x12\x14\n\ndataString\x18\x04 \x01(\t:\x00\x12\x12\n\x07\x64\x61taNum\x18\x05 \x01(\x03:\x01\x30\x12\x11\n\x06\x64\x61taID\x18\x06 \x01(\x03:\x01\x30\x12\x14\n\ttimeCheck\x18\x07 \x01(\x05:\x01\x30\x12H\n\x13sendComplianceFlags\x18\x08 \x01(\x0e\x32\x13.Policy.PolicyFlags:\x16SEND_IN_OUT_COMPLIANCE\x12\x0e\n\x06siteId\x18\t \x01(\t\x12\x16\n\x04uuid\x18\n \x01(\tB\x08\x82\xb5\x18\x04uuid\"\xdf\x01\n\x0bRunRuleFlag\x12\x12\n\x0eRUN_RULE_NEVER\x10\x00\x12\x14\n\x10RUN_RULE_STARTUP\x10\x01\x12\x15\n\x11RUN_RULE_SHUTDOWN\x10\x02\x12\x1a\n\x16RUN_RULE_PROCESS_START\x10\x04\x12\x18\n\x14RUN_RULE_PROCESS_END\x10\x08\x12 \n\x1cRUN_RULE_PROCESS_ENUMERATION\x10\x10\x12#\n\x1fRUN_RULE_NEW_NETWORK_CONNECTION\x10 \x12\x12\n\x0eRUN_RULE_TIMER\x10@\"\xb4\x01\n\x0bPolicyFlags\x12\x10\n\x0cSEND_NOTHING\x10\x00\x12\x16\n\x12SEND_IN_COMPLIANCE\x10\x01\x12\x17\n\x13SEND_OUT_COMPLIANCE\x10\x02\x12\x1a\n\x16SEND_IN_OUT_COMPLIANCE\x10\x03\x12\x13\n\x0fSEND_IS_RUNNING\x10\x04\x12\x16\n\x12SEND_ISNOT_RUNNING\x10\x08\x12\x19\n\x15SEND_IS_ISNOT_RUNNING\x10\x0c\x42\x33\n\"com.ziften.server.protocol.messageB\rPolicyMessage')



_POLICY_RUNRULEFLAG = _descriptor.EnumDescriptor(
  name='RunRuleFlag',
  full_name='Policy.RunRuleFlag',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RUN_RULE_NEVER', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUN_RULE_STARTUP', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUN_RULE_SHUTDOWN', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUN_RULE_PROCESS_START', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUN_RULE_PROCESS_END', index=4, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUN_RULE_PROCESS_ENUMERATION', index=5, number=16,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUN_RULE_NEW_NETWORK_CONNECTION', index=6, number=32,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUN_RULE_TIMER', index=7, number=64,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=357,
  serialized_end=580,
)

_POLICY_POLICYFLAGS = _descriptor.EnumDescriptor(
  name='PolicyFlags',
  full_name='Policy.PolicyFlags',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SEND_NOTHING', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEND_IN_COMPLIANCE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEND_OUT_COMPLIANCE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEND_IN_OUT_COMPLIANCE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEND_IS_RUNNING', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEND_ISNOT_RUNNING', index=5, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEND_IS_ISNOT_RUNNING', index=6, number=12,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=583,
  serialized_end=763,
)


_POLICY = _descriptor.Descriptor(
  name='Policy',
  full_name='Policy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='policyID', full_name='Policy.policyID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='runFlags', full_name='Policy.runFlags', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=64,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='method', full_name='Policy.method', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("CHECK_PROCESS_LIST", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dataString', full_name='Policy.dataString', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dataNum', full_name='Policy.dataNum', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dataID', full_name='Policy.dataID', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timeCheck', full_name='Policy.timeCheck', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sendComplianceFlags', full_name='Policy.sendComplianceFlags', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=3,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='siteId', full_name='Policy.siteId', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='Policy.uuid', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _POLICY_RUNRULEFLAG,
    _POLICY_POLICYFLAGS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=37,
  serialized_end=763,
)

_POLICY.fields_by_name['runFlags'].enum_type = _POLICY_RUNRULEFLAG
_POLICY.fields_by_name['sendComplianceFlags'].enum_type = _POLICY_POLICYFLAGS
_POLICY_RUNRULEFLAG.containing_type = _POLICY;
_POLICY_POLICYFLAGS.containing_type = _POLICY;
DESCRIPTOR.message_types_by_name['Policy'] = _POLICY

class Policy(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _POLICY

  # @@protoc_insertion_point(class_scope:Policy)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\"com.ziften.server.protocol.messageB\rPolicyMessage')
_POLICY.fields_by_name['uuid'].has_options = True
_POLICY.fields_by_name['uuid']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
# @@protoc_insertion_point(module_scope)
