# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PostgresType.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import google.protobuf.descriptor_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PostgresType.proto',
  package='',
  serialized_pb='\n\x12PostgresType.proto\x1a google/protobuf/descriptor.proto:5\n\x0cpostgresType\x12\x1d.google.protobuf.FieldOptions\x18\xd0\x86\x03 \x01(\tB2\n\"com.ziften.server.protocol.messageB\x0cPostgresType')


POSTGRESTYPE_FIELD_NUMBER = 50000
postgresType = _descriptor.FieldDescriptor(
  name='postgresType', full_name='postgresType', index=0,
  number=50000, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=unicode("", "utf-8"),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


google.protobuf.descriptor_pb2.FieldOptions.RegisterExtension(postgresType)

DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\"com.ziften.server.protocol.messageB\014PostgresType')
# @@protoc_insertion_point(module_scope)
