# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RemediateResponse.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = _descriptor.FileDescriptor(
  name='RemediateResponse.proto',
  package='',
  serialized_pb='\n\x17RemediateResponse.proto\x1a\x12PostgresType.proto\"\x8a\x03\n\x11RemediateResponse\x12 \n\ttimeStamp\x18\x01 \x02(\x03\x42\r\x82\xb5\x18\ttimestamp\x12\x1b\n\tagentGUID\x18\x02 \x02(\tB\x08\x82\xb5\x18\x04uuid\x12\x1d\n\x15remediationIdentifier\x18\x03 \x02(\x04\x12?\n\x11remediationResult\x18\x04 \x02(\x0e\x32$.RemediateResponse.RemediationResult\x12\x1d\n\x15remediationReturnCode\x18\x05 \x02(\x05\x12\x0e\n\x06siteId\x18\x06 \x01(\t\x12\x0b\n\x03md5\x18\x07 \x01(\t\x12\x16\n\x04uuid\x18\x08 \x01(\tB\x08\x82\xb5\x18\x04uuid\"\x81\x01\n\x11RemediationResult\x12\x17\n\x13REMEDIATION_SUCCESS\x10\x00\x12\x1e\n\x1aREMEDIATION_OBJECTNOTFOUND\x10\x01\x12\x15\n\x11REMEDIATION_ERROR\x10\x02\x12\x1c\n\x18REMEDIATION_ALREADY_DONE\x10\x03\x42>\n\"com.ziften.server.protocol.messageB\x18RemediateResponseMessage')



_REMEDIATERESPONSE_REMEDIATIONRESULT = _descriptor.EnumDescriptor(
  name='RemediationResult',
  full_name='RemediateResponse.RemediationResult',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REMEDIATION_SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REMEDIATION_OBJECTNOTFOUND', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REMEDIATION_ERROR', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REMEDIATION_ALREADY_DONE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=313,
  serialized_end=442,
)


_REMEDIATERESPONSE = _descriptor.Descriptor(
  name='RemediateResponse',
  full_name='RemediateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='RemediateResponse.timeStamp', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')),
    _descriptor.FieldDescriptor(
      name='agentGUID', full_name='RemediateResponse.agentGUID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='remediationIdentifier', full_name='RemediateResponse.remediationIdentifier', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='remediationResult', full_name='RemediateResponse.remediationResult', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='remediationReturnCode', full_name='RemediateResponse.remediationReturnCode', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='siteId', full_name='RemediateResponse.siteId', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='md5', full_name='RemediateResponse.md5', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='RemediateResponse.uuid', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REMEDIATERESPONSE_REMEDIATIONRESULT,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=48,
  serialized_end=442,
)

_REMEDIATERESPONSE.fields_by_name['remediationResult'].enum_type = _REMEDIATERESPONSE_REMEDIATIONRESULT
_REMEDIATERESPONSE_REMEDIATIONRESULT.containing_type = _REMEDIATERESPONSE;
DESCRIPTOR.message_types_by_name['RemediateResponse'] = _REMEDIATERESPONSE

class RemediateResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REMEDIATERESPONSE

  # @@protoc_insertion_point(class_scope:RemediateResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\"com.ziften.server.protocol.messageB\030RemediateResponseMessage')
_REMEDIATERESPONSE.fields_by_name['timeStamp'].has_options = True
_REMEDIATERESPONSE.fields_by_name['timeStamp']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')
_REMEDIATERESPONSE.fields_by_name['agentGUID'].has_options = True
_REMEDIATERESPONSE.fields_by_name['agentGUID']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
_REMEDIATERESPONSE.fields_by_name['uuid'].has_options = True
_REMEDIATERESPONSE.fields_by_name['uuid']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
# @@protoc_insertion_point(module_scope)
