# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SystemInventoryDiskDrives.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import PostgresType_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SystemInventoryDiskDrives.proto',
  package='',
  serialized_pb='\n\x1fSystemInventoryDiskDrives.proto\x1a\x12PostgresType.proto\"\xbf\x02\n\x19SystemInventoryDiskDrives\x12 \n\ttimeStamp\x18\x01 \x02(\x03\x42\r\x82\xb5\x18\ttimestamp\x12\x1b\n\tagentGUID\x18\x02 \x02(\tB\x08\x82\xb5\x18\x04uuid\x12 \n\x0e\x64iskDrivesGUID\x18\x03 \x02(\tB\x08\x82\xb5\x18\x04uuid\x12\r\n\x05model\x18\x04 \x03(\t\x12\x0f\n\x07\x63\x61ption\x18\x05 \x03(\t\x12\x10\n\x08\x64\x65viceID\x18\x06 \x03(\t\x12\x15\n\rinterfaceType\x18\x07 \x03(\t\x12\x18\n\x04size\x18\x08 \x03(\tB\n\x82\xb5\x18\x06\x62igint\x12\x0e\n\x06siteId\x18\t \x01(\t\x12\x13\n\x0bpnpDeviceID\x18\n \x03(\t\x12\x11\n\tserialNum\x18\x0b \x03(\t\x12\x0e\n\x06status\x18\x0c \x03(\t\x12\x16\n\x04uuid\x18\r \x01(\tB\x08\x82\xb5\x18\x04uuidBF\n\"com.ziften.server.protocol.messageB SystemInventoryDiskDrivesMessage')




_SYSTEMINVENTORYDISKDRIVES = _descriptor.Descriptor(
  name='SystemInventoryDiskDrives',
  full_name='SystemInventoryDiskDrives',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='SystemInventoryDiskDrives.timeStamp', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')),
    _descriptor.FieldDescriptor(
      name='agentGUID', full_name='SystemInventoryDiskDrives.agentGUID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='diskDrivesGUID', full_name='SystemInventoryDiskDrives.diskDrivesGUID', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='model', full_name='SystemInventoryDiskDrives.model', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='caption', full_name='SystemInventoryDiskDrives.caption', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deviceID', full_name='SystemInventoryDiskDrives.deviceID', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='interfaceType', full_name='SystemInventoryDiskDrives.interfaceType', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='SystemInventoryDiskDrives.size', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\006bigint')),
    _descriptor.FieldDescriptor(
      name='siteId', full_name='SystemInventoryDiskDrives.siteId', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pnpDeviceID', full_name='SystemInventoryDiskDrives.pnpDeviceID', index=9,
      number=10, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serialNum', full_name='SystemInventoryDiskDrives.serialNum', index=10,
      number=11, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='SystemInventoryDiskDrives.status', index=11,
      number=12, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='SystemInventoryDiskDrives.uuid', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=56,
  serialized_end=375,
)

DESCRIPTOR.message_types_by_name['SystemInventoryDiskDrives'] = _SYSTEMINVENTORYDISKDRIVES

class SystemInventoryDiskDrives(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SYSTEMINVENTORYDISKDRIVES

  # @@protoc_insertion_point(class_scope:SystemInventoryDiskDrives)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\"com.ziften.server.protocol.messageB SystemInventoryDiskDrivesMessage')
_SYSTEMINVENTORYDISKDRIVES.fields_by_name['timeStamp'].has_options = True
_SYSTEMINVENTORYDISKDRIVES.fields_by_name['timeStamp']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')
_SYSTEMINVENTORYDISKDRIVES.fields_by_name['agentGUID'].has_options = True
_SYSTEMINVENTORYDISKDRIVES.fields_by_name['agentGUID']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
_SYSTEMINVENTORYDISKDRIVES.fields_by_name['diskDrivesGUID'].has_options = True
_SYSTEMINVENTORYDISKDRIVES.fields_by_name['diskDrivesGUID']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
_SYSTEMINVENTORYDISKDRIVES.fields_by_name['size'].has_options = True
_SYSTEMINVENTORYDISKDRIVES.fields_by_name['size']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\006bigint')
_SYSTEMINVENTORYDISKDRIVES.fields_by_name['uuid'].has_options = True
_SYSTEMINVENTORYDISKDRIVES.fields_by_name['uuid']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
# @@protoc_insertion_point(module_scope)
