# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserAccounts.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import PostgresType_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='UserAccounts.proto',
  package='',
  serialized_pb='\n\x12UserAccounts.proto\x1a\x12PostgresType.proto\"\x8f\x07\n\x0cUserAccounts\x12 \n\ttimeStamp\x18\x01 \x02(\x03\x42\r\x82\xb5\x18\ttimestamp\x12\x1b\n\tagentGUID\x18\x02 \x02(\tB\x08\x82\xb5\x18\x04uuid\x12\x0e\n\x06siteId\x18\x03 \x01(\t\x12\x16\n\x04uuid\x18\x04 \x01(\tB\x08\x82\xb5\x18\x04uuid\x12\x0c\n\x04name\x18\x05 \x03(\t\x12\x14\n\x0cpassword_age\x18\x06 \x03(\r\x12)\n\x04priv\x18\x07 \x03(\x0e\x32\x1b.UserAccounts.PrivilegeType\x12\x10\n\x08home_dir\x18\x08 \x03(\t\x12\x0f\n\x07\x63omment\x18\t \x03(\t\x12\x13\n\x0bscript_path\x18\n \x03(\t\x12\x11\n\tfull_name\x18\x0c \x03(\t\x12\x13\n\x0busr_comment\x18\r \x03(\t\x12\r\n\x05parms\x18\x0e \x03(\t\x12\x14\n\x0cworkstations\x18\x0f \x03(\t\x12\x12\n\nlast_logon\x18\x10 \x03(\r\x12\x13\n\x0blast_logoff\x18\x11 \x03(\r\x12\x14\n\x0c\x61\x63\x63t_expires\x18\x12 \x03(\r\x12\x13\n\x0bmax_storage\x18\x13 \x03(\r\x12\x14\n\x0c\x62\x61\x64_pw_count\x18\x14 \x03(\r\x12\x12\n\nnum_logons\x18\x15 \x03(\r\x12\x14\n\x0clogon_server\x18\x16 \x03(\t\x12\x14\n\x0c\x63ountry_code\x18\x17 \x03(\r\x12\x11\n\tcode_page\x18\x18 \x03(\r\x12\x0f\n\x07user_id\x18\x19 \x03(\r\x12\x18\n\x10primary_group_id\x18\x1a \x03(\r\x12\x0f\n\x07profile\x18\x1b \x03(\t\x12\x16\n\x0ehome_dir_drive\x18\x1c \x03(\t\x12\x18\n\x10password_expired\x18\x1d \x03(\r\x12\x1d\n\x15member_of_print_group\x18\x1e \x03(\x08\x12\x1c\n\x14member_of_comm_group\x18\x1f \x03(\x08\x12\x1e\n\x16member_of_server_group\x18  \x03(\x08\x12 \n\x18member_of_accounts_group\x18! \x03(\x08\x12\x0b\n\x03sid\x18\" \x03(\t\x12\x10\n\x08\x64isabled\x18# \x03(\x08\x12\x11\n\tlockedOut\x18$ \x03(\x08\"h\n\rPrivilegeType\x12\x16\n\x12\x65USER_PRIV_UNKNOWN\x10\x00\x12\x14\n\x10\x65USER_PRIV_GUEST\x10\x01\x12\x13\n\x0f\x65USER_PRIV_USER\x10\x02\x12\x14\n\x10\x65USER_PRIV_ADMIN\x10\x03\x42\x39\n\"com.ziften.server.protocol.messageB\x13UserAccountsMessage')



_USERACCOUNTS_PRIVILEGETYPE = _descriptor.EnumDescriptor(
  name='PrivilegeType',
  full_name='UserAccounts.PrivilegeType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='eUSER_PRIV_UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eUSER_PRIV_GUEST', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eUSER_PRIV_USER', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eUSER_PRIV_ADMIN', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=850,
  serialized_end=954,
)


_USERACCOUNTS = _descriptor.Descriptor(
  name='UserAccounts',
  full_name='UserAccounts',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='UserAccounts.timeStamp', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')),
    _descriptor.FieldDescriptor(
      name='agentGUID', full_name='UserAccounts.agentGUID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='siteId', full_name='UserAccounts.siteId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='UserAccounts.uuid', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='name', full_name='UserAccounts.name', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password_age', full_name='UserAccounts.password_age', index=5,
      number=6, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='priv', full_name='UserAccounts.priv', index=6,
      number=7, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='home_dir', full_name='UserAccounts.home_dir', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='comment', full_name='UserAccounts.comment', index=8,
      number=9, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='script_path', full_name='UserAccounts.script_path', index=9,
      number=10, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='full_name', full_name='UserAccounts.full_name', index=10,
      number=12, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='usr_comment', full_name='UserAccounts.usr_comment', index=11,
      number=13, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parms', full_name='UserAccounts.parms', index=12,
      number=14, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='workstations', full_name='UserAccounts.workstations', index=13,
      number=15, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_logon', full_name='UserAccounts.last_logon', index=14,
      number=16, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_logoff', full_name='UserAccounts.last_logoff', index=15,
      number=17, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='acct_expires', full_name='UserAccounts.acct_expires', index=16,
      number=18, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_storage', full_name='UserAccounts.max_storage', index=17,
      number=19, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bad_pw_count', full_name='UserAccounts.bad_pw_count', index=18,
      number=20, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_logons', full_name='UserAccounts.num_logons', index=19,
      number=21, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='logon_server', full_name='UserAccounts.logon_server', index=20,
      number=22, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='country_code', full_name='UserAccounts.country_code', index=21,
      number=23, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code_page', full_name='UserAccounts.code_page', index=22,
      number=24, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='UserAccounts.user_id', index=23,
      number=25, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='primary_group_id', full_name='UserAccounts.primary_group_id', index=24,
      number=26, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='profile', full_name='UserAccounts.profile', index=25,
      number=27, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='home_dir_drive', full_name='UserAccounts.home_dir_drive', index=26,
      number=28, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password_expired', full_name='UserAccounts.password_expired', index=27,
      number=29, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='member_of_print_group', full_name='UserAccounts.member_of_print_group', index=28,
      number=30, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='member_of_comm_group', full_name='UserAccounts.member_of_comm_group', index=29,
      number=31, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='member_of_server_group', full_name='UserAccounts.member_of_server_group', index=30,
      number=32, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='member_of_accounts_group', full_name='UserAccounts.member_of_accounts_group', index=31,
      number=33, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sid', full_name='UserAccounts.sid', index=32,
      number=34, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='disabled', full_name='UserAccounts.disabled', index=33,
      number=35, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lockedOut', full_name='UserAccounts.lockedOut', index=34,
      number=36, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _USERACCOUNTS_PRIVILEGETYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=43,
  serialized_end=954,
)

_USERACCOUNTS.fields_by_name['priv'].enum_type = _USERACCOUNTS_PRIVILEGETYPE
_USERACCOUNTS_PRIVILEGETYPE.containing_type = _USERACCOUNTS;
DESCRIPTOR.message_types_by_name['UserAccounts'] = _USERACCOUNTS

class UserAccounts(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USERACCOUNTS

  # @@protoc_insertion_point(class_scope:UserAccounts)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\"com.ziften.server.protocol.messageB\023UserAccountsMessage')
_USERACCOUNTS.fields_by_name['timeStamp'].has_options = True
_USERACCOUNTS.fields_by_name['timeStamp']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')
_USERACCOUNTS.fields_by_name['agentGUID'].has_options = True
_USERACCOUNTS.fields_by_name['agentGUID']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
_USERACCOUNTS.fields_by_name['uuid'].has_options = True
_USERACCOUNTS.fields_by_name['uuid']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
# @@protoc_insertion_point(module_scope)
