# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WindowsUpdate.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import PostgresType_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WindowsUpdate.proto',
  package='',
  serialized_pb='\n\x13WindowsUpdate.proto\x1a\x12PostgresType.proto\"\xd6\x05\n\rWindowsUpdate\x12 \n\ttimeStamp\x18\x01 \x02(\x03\x42\r\x82\xb5\x18\ttimestamp\x12\x1b\n\tagentGUID\x18\x02 \x02(\tB\x08\x82\xb5\x18\x04uuid\x12\x1b\n\x13\x63lientApplicationID\x18\x03 \x03(\t\x12 \n\tdateLocal\x18\x04 \x03(\x03\x42\r\x82\xb5\x18\ttimestamp\x12\x1e\n\x07\x64\x61teUTC\x18\x05 \x03(\x03\x42\r\x82\xb5\x18\ttimestamp\x12\x13\n\x0b\x64\x65scription\x18\x06 \x03(\t\x12\x31\n\toperation\x18\x07 \x03(\x0e\x32\x1e.WindowsUpdate.UpdateOperation\x12\x36\n\nresultCode\x18\x08 \x03(\x0e\x32\".WindowsUpdate.OperationResultCode\x12\x11\n\tserviceID\x18\t \x03(\t\x12\x12\n\nsupportURL\x18\n \x03(\t\x12\r\n\x05title\x18\x0b \x03(\t\x12\x16\n\x0eupdateRevision\x18\x0c \x03(\x05\x12\x10\n\x08updateID\x18\r \x03(\t\x12\x14\n\x0c\x63\x61tegoryName\x18\x0e \x03(\t\x12\x14\n\x0c\x63\x61tegoryType\x18\x0f \x03(\t\x12\x0c\n\x04kbID\x18\x10 \x03(\t\x12\x0e\n\x06siteId\x18\x11 \x01(\t\x12\x16\n\x04uuid\x18\x12 \x01(\tB\x08\x82\xb5\x18\x04uuid\x12\x1d\n\x0bwuaScanUUID\x18\x13 \x01(\tB\x08\x82\xb5\x18\x04uuid\";\n\x0fUpdateOperation\x12\x12\n\x0euoInstallation\x10\x01\x12\x14\n\x10uoUninstallation\x10\x02\"\x88\x01\n\x13OperationResultCode\x12\x11\n\rorcNotStarted\x10\x00\x12\x11\n\rorcInProgress\x10\x01\x12\x10\n\x0corcSucceeded\x10\x02\x12\x1a\n\x16orcSucceededWithErrors\x10\x03\x12\r\n\torcFailed\x10\x04\x12\x0e\n\norcAborted\x10\x05\x42:\n\"com.ziften.server.protocol.messageB\x14WindowsUpdateMessage')



_WINDOWSUPDATE_UPDATEOPERATION = _descriptor.EnumDescriptor(
  name='UpdateOperation',
  full_name='WindowsUpdate.UpdateOperation',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='uoInstallation', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='uoUninstallation', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=572,
  serialized_end=631,
)

_WINDOWSUPDATE_OPERATIONRESULTCODE = _descriptor.EnumDescriptor(
  name='OperationResultCode',
  full_name='WindowsUpdate.OperationResultCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='orcNotStarted', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='orcInProgress', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='orcSucceeded', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='orcSucceededWithErrors', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='orcFailed', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='orcAborted', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=634,
  serialized_end=770,
)


_WINDOWSUPDATE = _descriptor.Descriptor(
  name='WindowsUpdate',
  full_name='WindowsUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='WindowsUpdate.timeStamp', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')),
    _descriptor.FieldDescriptor(
      name='agentGUID', full_name='WindowsUpdate.agentGUID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='clientApplicationID', full_name='WindowsUpdate.clientApplicationID', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dateLocal', full_name='WindowsUpdate.dateLocal', index=3,
      number=4, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')),
    _descriptor.FieldDescriptor(
      name='dateUTC', full_name='WindowsUpdate.dateUTC', index=4,
      number=5, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')),
    _descriptor.FieldDescriptor(
      name='description', full_name='WindowsUpdate.description', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='operation', full_name='WindowsUpdate.operation', index=6,
      number=7, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resultCode', full_name='WindowsUpdate.resultCode', index=7,
      number=8, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serviceID', full_name='WindowsUpdate.serviceID', index=8,
      number=9, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='supportURL', full_name='WindowsUpdate.supportURL', index=9,
      number=10, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='title', full_name='WindowsUpdate.title', index=10,
      number=11, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='updateRevision', full_name='WindowsUpdate.updateRevision', index=11,
      number=12, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='updateID', full_name='WindowsUpdate.updateID', index=12,
      number=13, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='categoryName', full_name='WindowsUpdate.categoryName', index=13,
      number=14, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='categoryType', full_name='WindowsUpdate.categoryType', index=14,
      number=15, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kbID', full_name='WindowsUpdate.kbID', index=15,
      number=16, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='siteId', full_name='WindowsUpdate.siteId', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='WindowsUpdate.uuid', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
    _descriptor.FieldDescriptor(
      name='wuaScanUUID', full_name='WindowsUpdate.wuaScanUUID', index=18,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _WINDOWSUPDATE_UPDATEOPERATION,
    _WINDOWSUPDATE_OPERATIONRESULTCODE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=44,
  serialized_end=770,
)

_WINDOWSUPDATE.fields_by_name['operation'].enum_type = _WINDOWSUPDATE_UPDATEOPERATION
_WINDOWSUPDATE.fields_by_name['resultCode'].enum_type = _WINDOWSUPDATE_OPERATIONRESULTCODE
_WINDOWSUPDATE_UPDATEOPERATION.containing_type = _WINDOWSUPDATE;
_WINDOWSUPDATE_OPERATIONRESULTCODE.containing_type = _WINDOWSUPDATE;
DESCRIPTOR.message_types_by_name['WindowsUpdate'] = _WINDOWSUPDATE

class WindowsUpdate(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WINDOWSUPDATE

  # @@protoc_insertion_point(class_scope:WindowsUpdate)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\"com.ziften.server.protocol.messageB\024WindowsUpdateMessage')
_WINDOWSUPDATE.fields_by_name['timeStamp'].has_options = True
_WINDOWSUPDATE.fields_by_name['timeStamp']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')
_WINDOWSUPDATE.fields_by_name['agentGUID'].has_options = True
_WINDOWSUPDATE.fields_by_name['agentGUID']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
_WINDOWSUPDATE.fields_by_name['dateLocal'].has_options = True
_WINDOWSUPDATE.fields_by_name['dateLocal']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')
_WINDOWSUPDATE.fields_by_name['dateUTC'].has_options = True
_WINDOWSUPDATE.fields_by_name['dateUTC']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\ttimestamp')
_WINDOWSUPDATE.fields_by_name['uuid'].has_options = True
_WINDOWSUPDATE.fields_by_name['uuid']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
_WINDOWSUPDATE.fields_by_name['wuaScanUUID'].has_options = True
_WINDOWSUPDATE.fields_by_name['wuaScanUUID']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\202\265\030\004uuid')
# @@protoc_insertion_point(module_scope)
