# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 02:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [(b'datacollection', '0001_initial')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_time', models.DateTimeField(default=datetime.datetime(2016, 2, 11, 2, 47, 1, 776861))),
                ('message', models.BinaryField()),
            ],
        ),
    ]
