# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0001_squashed_0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmessage',
            name='insert_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
