# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 03:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0002_auto_20160211_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmessage',
            name='message_type',
            field=models.TextField(default=datetime.datetime(2016, 2, 11, 3, 52, 3, 388070, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
