# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0003_agentmessage_message_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedMesssage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('message_type', models.TextField()),
                ('message', models.BinaryField()),
                ('is_delivered', models.BooleanField(default=False)),
            ],
        ),
    ]
