# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0004_queuedmesssage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerShellScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('parameterJSON', models.TextField()),
                ('schedule', models.IntegerField()),
                ('run_periodically_sec', models.IntegerField()),
            ],
        ),
    ]
