# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0007_auto_20160218_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='powershellscript',
            name='filename',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
