# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0008_powershellscript_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='powershellscriptconfig',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='powershellscript',
            name='filename',
            field=models.CharField(choices=[('BlockAllOn.zep', 'BlockAllOn.zep'), ('CheckSizeOutlookFiles.zep', 'CheckSizeOutlookFiles.zep'), ('CollectAvailableWirelessNetworks.zep', 'CollectAvailableWirelessNetworks.zep'), ('DNSEnforcement.zep', 'DNSEnforcement.zep'), ('DNSFromDHCP.zep', 'DNSFromDHCP.zep'), ('DynamicScript.zep', 'DynamicScript.zep'), ('GetCertificateInfo.zep', 'GetCertificateInfo.zep'), ('GetRegKeyValues.zep', 'GetRegKeyValues.zep'), ('GetSystemMemory.zep', 'GetSystemMemory.zep'), ('KillPID.zep', 'KillPID.zep'), ('WatchAndKillProcesses.zep', 'WatchAndKillProcesses.zep'), ('WatchStartups.zep', 'WatchStartups.zep')], max_length=255),
        ),
    ]
