# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0009_auto_20160218_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powershellscriptconfig',
            name='parameterJSON',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='powershellscriptconfig',
            name='run_periodically_sec',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='powershellscriptconfig',
            name='schedule',
            field=models.IntegerField(choices=[(1, 'Once (1)'), (2, 'On Idle (2)'), (3, 'Periodically (3)'), (4, 'OnDemand (4)')], default=1),
        ),
        migrations.AlterField(
            model_name='queuedmesssage',
            name='message',
            field=models.TextField(),
        ),
    ]
