# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0010_auto_20160218_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuedmesssage',
            name='message',
            field=models.BinaryField(),
        ),
    ]
