# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-13 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0011_auto_20160218_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmessage',
            name='agentGUID',
            field=models.TextField(default=''),
        ),
    ]
