# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-13 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0012_agentmessage_agentguid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentmessage',
            old_name='agentGUID',
            new_name='agentguid',
        ),
    ]
