# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-13 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0013_auto_20160913_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuedmesssage',
            name='agentguid',
            field=models.TextField(default=''),
        ),
    ]
