# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-15 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0014_queuedmesssage_agentguid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField()),
                ('zep', models.TextField()),
                ('extension_text', models.TextField()),
                ('extension_b64', models.TextField()),
            ],
        ),
    ]
