#! /bin/sh

VIRTUALENV=/usr/local/bin/python2.7
APP_PATH=/opt/concentrator/
NAME=concentrator
DESC="Ziften Concentrator"
PID_FILE=/opt/concentrator/web.pid

############### END EDIT ME ##################

case "$1" in
  start)
        echo -n "Starting $DESC: "
        if [[ ! -f $PID_FILE ]]; then
            /opt/concentrator/start.sh > /dev/null & echo $! > $PID_FILE
        fi
        echo "$NAME."
        ;;
  stop)
        echo -n "Stopping $DESC: "
	/opt/concentrator/stop.sh >/dev/null
  	if [[ -f $PID_FILE ]]; then
	    rm $PID_FILE
        fi


        echo "$NAME."
        ;;

  restart|force-reload)
        echo -n "Restarting $DESC: "
  	if [[ -f $PID_FILE ]]; then
	    rm $PID_FILE
        fi
	/opt/concentrator/stop.sh 
	sleep 2
        if [[ ! -f $PID_FILE ]]; then
            /opt/concentrator/start.sh > /dev/null & echo $! > $PID_FILE
        fi
        echo "$NAME."
        ;;
  *)
        echo "Usage: $N {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
