#! /bin/sh

VIRTUALENV=/usr/local/bin/python2.7
APP_PATH=/opt/concentrator/
NAME=concentrator
DESC="Ziften Concentrator"
PID_FILE=/opt/concentrator/web.pid

############### END EDIT ME ##################

case "$1" in
  start)
        echo -n "Starting $DESC: "
        if [[ ! -f $PID_FILE ]]; then
            $APP_PATH/start.sh > /dev/null & echo -$! > $PID_FILE
        fi
        echo "$NAME."
        ;;
  stop)
        echo -n "Stopping $DESC: "
	/opt/concentrator/stop.sh >/dev/null
        echo "$NAME."
        ;;

  restart|force-reload)
        echo -n "Restarting $DESC: "
        kill -HUP $(cat $PID_FILE 2> /dev/null) || true
        sleep 1
        $APP_PATH/start.sh > /dev/null & echo $! > $PID_FILE
        echo "$NAME."
        ;;
  *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
